package com.nju.sdpt.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "npForDzfyServicePortType", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/")
public interface NpForDzfyServicePortType {

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/")
	@RequestWrapper(localName = "getWslaList", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.GetWslaList")
	@ResponseWrapper(localName = "getWslaListResponse", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.GetWslaListResponse")
	public String getWslaList(
            @WebParam(name = "in0", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in0);

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "CreateDzsd")
	@WebResult(name = "out", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/")
	@RequestWrapper(localName = "CreateDzsd", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.CreateDzsd")
	@ResponseWrapper(localName = "CreateDzsdResponse", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.CreateDzsdResponse")
	public String createDzsd(
            @WebParam(name = "in0", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in0,
            @WebParam(name = "in1", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in1,
            @WebParam(name = "in2", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in2);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/")
	@RequestWrapper(localName = "getWsjfList", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.GetWsjfList")
	@ResponseWrapper(localName = "getWsjfListResponse", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.GetWsjfListResponse")
	public String getWsjfList(
            @WebParam(name = "in0", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in0);


	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/")
	@RequestWrapper(localName = "payFeedBack", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.PayFeedBack")
	@ResponseWrapper(localName = "payFeedBackResponse", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.PayFeedBackResponse")
	public String payFeedBack(
            @WebParam(name = "in0", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/")
	@RequestWrapper(localName = "getLayyShxxList", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.GetLayyShxxList")
	@ResponseWrapper(localName = "getLayyShxxListResponse", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.GetLayyShxxListResponse")
	public String getLayyShxxList(
            @WebParam(name = "in0", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/")
	@RequestWrapper(localName = "sendZjcl", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.SendZjcl")
	@ResponseWrapper(localName = "sendZjclResponse", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/", className = "software.tjspxt.webservice.dzsd.SendZjclResponse")
	public String sendZjcl(
            @WebParam(name = "in0", targetNamespace = "http://impl.sfgk.dwjk.fy.np.thunisoft.com/") String in0);

}
