package com.nju.sdpt.service;

import com.nju.sdpt.entity.PubDbrwInfoEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DbrwService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int insert(PubDbrwInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PubDbrwInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    PubDbrwInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubDbrwInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubDbrwInfoEntity record);


    List<PubDbrwInfoEntity> dbrwList( String clzt, Integer yhbh,  String xzsdfs);

    Boolean updateLylqById( String xq ,Integer id);

    Boolean updatestatusById(@Param( "id") Integer id);

}
