package com.nju.sdpt.service;

import com.nju.sdpt.entity.PubKdtdEntity;
import com.nju.sdpt.entity.RpoEmsInfoEntity;

public interface RpoEmsInfoService {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int insert(RpoEmsInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int insertSelective(RpoEmsInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    RpoEmsInfoEntity selectByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RpoEmsInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RpoEmsInfoEntity record);

    void uploadSdjg(PubKdtdEntity pubKdtdEntity);
}
