
package com.nju.sdpt.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SNPServiceV2HttpGet", targetNamespace = "SnPrintAPIEntity")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SNPServiceV2HttpGet {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld")
    @WebResult(name = "string", targetNamespace = "SnPrintAPIEntity", partName = "Body")
    public String helloWorld();

    /**
     * 服务接口主函数
     * 
     * @param strXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SNPWEBRequest")
    @WebResult(name = "string", targetNamespace = "SnPrintAPIEntity", partName = "Body")
    public String snpwebRequest(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "strXML")
                    String strXML);

    /**
     * 接口帮助函数，生成接口调用输入参数(XML文档)示例，可以用于初始构建XML文档对象
     * 
     * @param iREQOPTION
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRequestXMLSampleByOPTION")
    @WebResult(name = "string", targetNamespace = "SnPrintAPIEntity", partName = "Body")
    public String getRequestXMLSampleByOPTION(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "iREQ_OPTION")
                    String iREQOPTION);

}
