package com.nju.sdpt.service;


import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SNPServiceV2Soap", targetNamespace = "SnPrintAPIEntity")
public interface SNPServiceV2Soap {


    /**
     *
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "SnPrintAPIEntity/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "SnPrintAPIEntity")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "SnPrintAPIEntity", className = "TestStamp.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "SnPrintAPIEntity", className = "TestStamp.HelloWorldResponse")
    public String helloWorld();

    /**
     * 服务接口主函数
     *
     * @param strXML
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SNPWEBRequest", action = "SnPrintAPIEntity/SNPWEBRequest")
    @WebResult(name = "SNPWEBRequestResult", targetNamespace = "SnPrintAPIEntity")
    @RequestWrapper(localName = "SNPWEBRequest", targetNamespace = "SnPrintAPIEntity", className = "TestStamp.SNPWEBRequest")
    @ResponseWrapper(localName = "SNPWEBRequestResponse", targetNamespace = "SnPrintAPIEntity", className = "TestStamp.SNPWEBRequestResponse")
    public String snpwebRequest(
            @WebParam(name = "strXML", targetNamespace = "SnPrintAPIEntity")
                    String strXML);

    /**
     * 接口帮助函数，生成接口调用输入参数(XML文档)示例，可以用于初始构建XML文档对象
     *
     * @param iREQOPTION
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetRequestXMLSampleByOPTION", action = "SnPrintAPIEntity/GetRequestXMLSampleByOPTION")
    @WebResult(name = "GetRequestXMLSampleByOPTIONResult", targetNamespace = "SnPrintAPIEntity")
    @RequestWrapper(localName = "GetRequestXMLSampleByOPTION", targetNamespace = "SnPrintAPIEntity", className = "TestStamp.GetRequestXMLSampleByOPTION")
    @ResponseWrapper(localName = "GetRequestXMLSampleByOPTIONResponse", targetNamespace = "SnPrintAPIEntity", className = "TestStamp.GetRequestXMLSampleByOPTIONResponse")
    public String getRequestXMLSampleByOPTION(
            @WebParam(name = "iREQ_OPTION", targetNamespace = "SnPrintAPIEntity")
                    int iREQOPTION);

}
