package com.nju.sdpt.service;


import com.nju.sdpt.entity.*;
import com.nju.sdpt.model.PubYysdSsdrModel;
import com.nju.sdpt.model.RetObj;
import com.nju.sdpt.viewobject.*;

import java.util.List;

public interface SsdrService {
    /**
     * 根据条件查询受送达人信息
     *
     * @param querySsdrListVo
     * @return
     */
    default List<PubYysdSsdrModel> querySsdrList(QuerySsdrListVo querySsdrListVo) {
        return null;
    }

    List<PubYysdSsdrModel> findByYysdbh(Integer yysdbh);

    /**
     * 工单-录入受送达人数据
     * 联系电话/地址/身份证
     * @param inputDataSsdrVo
     * @param yhm
     * @return
     */
    RetObj inputData(InputDataSsdrVo inputDataSsdrVo, String yhm);


    List<PubWebCallInfoEntity> queryHisWebCall(QuerySsdrHisDataVo querySsdrHisDataVo);

    List<PubDxtzInfoEntity> queryHisDxtz(QuerySsdrHisDataVo querySsdrHisDataVo);

    List<PubLylqInfoEntity> queryHisLy(QuerySsdrHisDataVo querySsdrHisDataVo);

    List<PubZjsdInfoEntity> queryHisZj(QuerySsdrHisDataVo querySsdrHisDataVo);

    /**
     * 修改送达达人送达结果
     * @param yysdbh
     * @param ssdrbh
     * @param fybh
     * @return 最终结果
     */
    String loadSsdrSdjg(Integer yysdbh, Integer ssdrbh, String fybh);

    PubYysdSsdrEntity findByYysdbhAndSsdrbh(Integer yysdbh, Integer ssdrbh);

    String readSdzt(Integer sdjg);

    void updateSdjgByYysdbhAndSsdrbh(Integer yysdbh, Integer ssdrbh, Integer sdjg);
    Integer savePubSsdrHmEntity(PubSsdrHmEntity pubSsdrHmEntity);
    Integer savePubYysdSsdrdzEntity(PubYysdSsdrdzEntity pubYysdSsdrdzEntity);

    List<SsdrVO> getSsdrxxByAjxhAndFybhAndDsrbh(Integer ajxh, String fybh);
    int updateByPrimaryKey(PubYysdSsdrEntity pubYysdSsdrEntity);

    //绑定法官历史填充的当事人信息
    void bindHisDsrxx(Integer ajxh, String fybh, List<DsrjbVO> dsrjbVOS);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR
     *
     * @mbggenerated
     */

    int deleteByPrimaryKey(PubYysdSsdrEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR
     *
     * @mbggenerated
     */
    int insert(PubYysdSsdrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR
     *
     * @mbggenerated
     */
    int insertSelective(PubYysdSsdrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR
     *
     * @mbggenerated
     */

    PubYysdSsdrEntity selectByPrimaryKey(PubYysdSsdrEntityKey key);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubYysdSsdrEntity record);

}
