package com.nju.sdpt.service;

import com.nju.sdpt.entity.PubSsdrHmEntity;

public interface SsdrHmService {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SSDR_HM
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SSDR_HM
     *
     * @mbggenerated
     */
    int insert(PubSsdrHmEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SSDR_HM
     *
     * @mbggenerated
     */
    int insertSelective(PubSsdrHmEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SSDR_HM
     *
     * @mbggenerated
     */
    PubSsdrHmEntity selectByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SSDR_HM
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubSsdrHmEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_SSDR_HM
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubSsdrHmEntity record);

}
