package com.nju.sdpt.entity;

import java.util.Date;

public class AjJbEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AH
     *
     * @mbggenerated
     */
    private String ah;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AJMC
     *
     * @mbggenerated
     */
    private String ajmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AJXZ
     *
     * @mbggenerated
     */
    private String ajxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AJLY
     *
     * @mbggenerated
     */
    private String ajly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SPCX
     *
     * @mbggenerated
     */
    private String spcx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SPCXDZ
     *
     * @mbggenerated
     */
    private String spcxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SYCX
     *
     * @mbggenerated
     */
    private String sycx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFYS
     *
     * @mbggenerated
     */
    private String sfys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFZDAJ
     *
     * @mbggenerated
     */
    private String sfzdaj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFJBAJ
     *
     * @mbggenerated
     */
    private String sfjbaj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFFHCS
     *
     * @mbggenerated
     */
    private String sffhcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFWDYJ
     *
     * @mbggenerated
     */
    private String sfwdyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SX
     *
     * @mbggenerated
     */
    private Integer sx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.FJSX
     *
     * @mbggenerated
     */
    private Integer fjsx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.LYDQ
     *
     * @mbggenerated
     */
    private String lydq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.BASPT
     *
     * @mbggenerated
     */
    private String baspt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.LARQ
     *
     * @mbggenerated
     */
    private Date larq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.LAR
     *
     * @mbggenerated
     */
    private String lar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.BAFY
     *
     * @mbggenerated
     */
    private String bafy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.GKSJG
     *
     * @mbggenerated
     */
    private String gksjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.JARQ
     *
     * @mbggenerated
     */
    private Date jarq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.JAFS
     *
     * @mbggenerated
     */
    private String jafs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.JAYY
     *
     * @mbggenerated
     */
    private String jayy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.JAYYDM
     *
     * @mbggenerated
     */
    private String jayydm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SXRQ
     *
     * @mbggenerated
     */
    private Date sxrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.GDBZ
     *
     * @mbggenerated
     */
    private String gdbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AJZT
     *
     * @mbggenerated
     */
    private String ajzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.BYCXDZ
     *
     * @mbggenerated
     */
    private String bycxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AJWSQK
     *
     * @mbggenerated
     */
    private String ajwsqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.GDRQ
     *
     * @mbggenerated
     */
    private Date gdrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.GDXLH
     *
     * @mbggenerated
     */
    private Integer gdxlh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.CBRBPRQ
     *
     * @mbggenerated
     */
    private Date cbrbprq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.JJAR
     *
     * @mbggenerated
     */
    private String jjar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SPZSQRQ
     *
     * @mbggenerated
     */
    private Date spzsqrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.HYTHYRQ
     *
     * @mbggenerated
     */
    private Date hythyrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.TZSQRQ
     *
     * @mbggenerated
     */
    private Date tzsqrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.YZSQRQ
     *
     * @mbggenerated
     */
    private Date yzsqrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SWHJDRQ
     *
     * @mbggenerated
     */
    private Date swhjdrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.YZQFRQ
     *
     * @mbggenerated
     */
    private Date yzqfrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SLQK
     *
     * @mbggenerated
     */
    private String slqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SSLX
     *
     * @mbggenerated
     */
    private String sslx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFGS
     *
     * @mbggenerated
     */
    private String sfgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.FHCSYY
     *
     * @mbggenerated
     */
    private String fhcsyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.GPYY
     *
     * @mbggenerated
     */
    private String gpyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFZSCQ
     *
     * @mbggenerated
     */
    private String sfzscq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SWLX
     *
     * @mbggenerated
     */
    private String swlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.MODFLAG
     *
     * @mbggenerated
     */
    private String modflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.TRANSFLAG
     *
     * @mbggenerated
     */
    private String transflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SPTG
     *
     * @mbggenerated
     */
    private Integer sptg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.PSYCY
     *
     * @mbggenerated
     */
    private String psycy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.MSAJTJS
     *
     * @mbggenerated
     */
    private String msajtjs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.MSAJTJSSS
     *
     * @mbggenerated
     */
    private String msajtjsss;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SHWDFXPG
     *
     * @mbggenerated
     */
    private String shwdfxpg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFXESS
     *
     * @mbggenerated
     */
    private String sfxess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFFCXX
     *
     * @mbggenerated
     */
    private String sffcxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFCQYSCS
     *
     * @mbggenerated
     */
    private String sfcqyscs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.FXHJCS
     *
     * @mbggenerated
     */
    private String fxhjcs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.PJSFFDJFNR
     *
     * @mbggenerated
     */
    private String pjsffdjfnr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFDTPJ
     *
     * @mbggenerated
     */
    private String sfdtpj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFHJ
     *
     * @mbggenerated
     */
    private String sfhj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFKTSL
     *
     * @mbggenerated
     */
    private String sfktsl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFTZ
     *
     * @mbggenerated
     */
    private String sftz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.AJSFYS
     *
     * @mbggenerated
     */
    private String ajsfys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.RMPSYXM
     *
     * @mbggenerated
     */
    private String rmpsyxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.RMPSYID
     *
     * @mbggenerated
     */
    private String rmpsyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SFXSSC
     *
     * @mbggenerated
     */
    private String sfxssc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.LYBM
     *
     * @mbggenerated
     */
    private String lybm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.WJAWSYY
     *
     * @mbggenerated
     */
    private String wjawsyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.PJJG
     *
     * @mbggenerated
     */
    private String pjjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.JATHYY
     *
     * @mbggenerated
     */
    private String jathyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.RZRFCKCX
     *
     * @mbggenerated
     */
    private String rzrfckcx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.JYAQ
     *
     * @mbggenerated
     */
    private String jyaq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.CBRYJ
     *
     * @mbggenerated
     */
    private String cbryj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.HYTYJ
     *
     * @mbggenerated
     */
    private String hytyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.TZHYJ
     *
     * @mbggenerated
     */
    private String tzhyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.YZHYJ
     *
     * @mbggenerated
     */
    private String yzhyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_AJ_JB.SWHYJ
     *
     * @mbggenerated
     */
    private String swhyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PUB_AJ_JB
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AJXH
     *
     * @return the value of PUB_AJ_JB.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AJXH
     *
     * @param ajxh the value for PUB_AJ_JB.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AH
     *
     * @return the value of PUB_AJ_JB.AH
     *
     * @mbggenerated
     */
    public String getAh() {
        return ah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AH
     *
     * @param ah the value for PUB_AJ_JB.AH
     *
     * @mbggenerated
     */
    public void setAh(String ah) {
        this.ah = ah == null ? null : ah.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AJMC
     *
     * @return the value of PUB_AJ_JB.AJMC
     *
     * @mbggenerated
     */
    public String getAjmc() {
        return ajmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AJMC
     *
     * @param ajmc the value for PUB_AJ_JB.AJMC
     *
     * @mbggenerated
     */
    public void setAjmc(String ajmc) {
        this.ajmc = ajmc == null ? null : ajmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AJXZ
     *
     * @return the value of PUB_AJ_JB.AJXZ
     *
     * @mbggenerated
     */
    public String getAjxz() {
        return ajxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AJXZ
     *
     * @param ajxz the value for PUB_AJ_JB.AJXZ
     *
     * @mbggenerated
     */
    public void setAjxz(String ajxz) {
        this.ajxz = ajxz == null ? null : ajxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AJLY
     *
     * @return the value of PUB_AJ_JB.AJLY
     *
     * @mbggenerated
     */
    public String getAjly() {
        return ajly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AJLY
     *
     * @param ajly the value for PUB_AJ_JB.AJLY
     *
     * @mbggenerated
     */
    public void setAjly(String ajly) {
        this.ajly = ajly == null ? null : ajly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SPCX
     *
     * @return the value of PUB_AJ_JB.SPCX
     *
     * @mbggenerated
     */
    public String getSpcx() {
        return spcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SPCX
     *
     * @param spcx the value for PUB_AJ_JB.SPCX
     *
     * @mbggenerated
     */
    public void setSpcx(String spcx) {
        this.spcx = spcx == null ? null : spcx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SPCXDZ
     *
     * @return the value of PUB_AJ_JB.SPCXDZ
     *
     * @mbggenerated
     */
    public String getSpcxdz() {
        return spcxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SPCXDZ
     *
     * @param spcxdz the value for PUB_AJ_JB.SPCXDZ
     *
     * @mbggenerated
     */
    public void setSpcxdz(String spcxdz) {
        this.spcxdz = spcxdz == null ? null : spcxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SYCX
     *
     * @return the value of PUB_AJ_JB.SYCX
     *
     * @mbggenerated
     */
    public String getSycx() {
        return sycx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SYCX
     *
     * @param sycx the value for PUB_AJ_JB.SYCX
     *
     * @mbggenerated
     */
    public void setSycx(String sycx) {
        this.sycx = sycx == null ? null : sycx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFYS
     *
     * @return the value of PUB_AJ_JB.SFYS
     *
     * @mbggenerated
     */
    public String getSfys() {
        return sfys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFYS
     *
     * @param sfys the value for PUB_AJ_JB.SFYS
     *
     * @mbggenerated
     */
    public void setSfys(String sfys) {
        this.sfys = sfys == null ? null : sfys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFZDAJ
     *
     * @return the value of PUB_AJ_JB.SFZDAJ
     *
     * @mbggenerated
     */
    public String getSfzdaj() {
        return sfzdaj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFZDAJ
     *
     * @param sfzdaj the value for PUB_AJ_JB.SFZDAJ
     *
     * @mbggenerated
     */
    public void setSfzdaj(String sfzdaj) {
        this.sfzdaj = sfzdaj == null ? null : sfzdaj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFJBAJ
     *
     * @return the value of PUB_AJ_JB.SFJBAJ
     *
     * @mbggenerated
     */
    public String getSfjbaj() {
        return sfjbaj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFJBAJ
     *
     * @param sfjbaj the value for PUB_AJ_JB.SFJBAJ
     *
     * @mbggenerated
     */
    public void setSfjbaj(String sfjbaj) {
        this.sfjbaj = sfjbaj == null ? null : sfjbaj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFFHCS
     *
     * @return the value of PUB_AJ_JB.SFFHCS
     *
     * @mbggenerated
     */
    public String getSffhcs() {
        return sffhcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFFHCS
     *
     * @param sffhcs the value for PUB_AJ_JB.SFFHCS
     *
     * @mbggenerated
     */
    public void setSffhcs(String sffhcs) {
        this.sffhcs = sffhcs == null ? null : sffhcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFWDYJ
     *
     * @return the value of PUB_AJ_JB.SFWDYJ
     *
     * @mbggenerated
     */
    public String getSfwdyj() {
        return sfwdyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFWDYJ
     *
     * @param sfwdyj the value for PUB_AJ_JB.SFWDYJ
     *
     * @mbggenerated
     */
    public void setSfwdyj(String sfwdyj) {
        this.sfwdyj = sfwdyj == null ? null : sfwdyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SX
     *
     * @return the value of PUB_AJ_JB.SX
     *
     * @mbggenerated
     */
    public Integer getSx() {
        return sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SX
     *
     * @param sx the value for PUB_AJ_JB.SX
     *
     * @mbggenerated
     */
    public void setSx(Integer sx) {
        this.sx = sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.FJSX
     *
     * @return the value of PUB_AJ_JB.FJSX
     *
     * @mbggenerated
     */
    public Integer getFjsx() {
        return fjsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.FJSX
     *
     * @param fjsx the value for PUB_AJ_JB.FJSX
     *
     * @mbggenerated
     */
    public void setFjsx(Integer fjsx) {
        this.fjsx = fjsx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.LYDQ
     *
     * @return the value of PUB_AJ_JB.LYDQ
     *
     * @mbggenerated
     */
    public String getLydq() {
        return lydq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.LYDQ
     *
     * @param lydq the value for PUB_AJ_JB.LYDQ
     *
     * @mbggenerated
     */
    public void setLydq(String lydq) {
        this.lydq = lydq == null ? null : lydq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.BASPT
     *
     * @return the value of PUB_AJ_JB.BASPT
     *
     * @mbggenerated
     */
    public String getBaspt() {
        return baspt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.BASPT
     *
     * @param baspt the value for PUB_AJ_JB.BASPT
     *
     * @mbggenerated
     */
    public void setBaspt(String baspt) {
        this.baspt = baspt == null ? null : baspt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.LARQ
     *
     * @return the value of PUB_AJ_JB.LARQ
     *
     * @mbggenerated
     */
    public Date getLarq() {
        return larq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.LARQ
     *
     * @param larq the value for PUB_AJ_JB.LARQ
     *
     * @mbggenerated
     */
    public void setLarq(Date larq) {
        this.larq = larq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.LAR
     *
     * @return the value of PUB_AJ_JB.LAR
     *
     * @mbggenerated
     */
    public String getLar() {
        return lar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.LAR
     *
     * @param lar the value for PUB_AJ_JB.LAR
     *
     * @mbggenerated
     */
    public void setLar(String lar) {
        this.lar = lar == null ? null : lar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.BAFY
     *
     * @return the value of PUB_AJ_JB.BAFY
     *
     * @mbggenerated
     */
    public String getBafy() {
        return bafy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.BAFY
     *
     * @param bafy the value for PUB_AJ_JB.BAFY
     *
     * @mbggenerated
     */
    public void setBafy(String bafy) {
        this.bafy = bafy == null ? null : bafy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.GKSJG
     *
     * @return the value of PUB_AJ_JB.GKSJG
     *
     * @mbggenerated
     */
    public String getGksjg() {
        return gksjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.GKSJG
     *
     * @param gksjg the value for PUB_AJ_JB.GKSJG
     *
     * @mbggenerated
     */
    public void setGksjg(String gksjg) {
        this.gksjg = gksjg == null ? null : gksjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.JARQ
     *
     * @return the value of PUB_AJ_JB.JARQ
     *
     * @mbggenerated
     */
    public Date getJarq() {
        return jarq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.JARQ
     *
     * @param jarq the value for PUB_AJ_JB.JARQ
     *
     * @mbggenerated
     */
    public void setJarq(Date jarq) {
        this.jarq = jarq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.JAFS
     *
     * @return the value of PUB_AJ_JB.JAFS
     *
     * @mbggenerated
     */
    public String getJafs() {
        return jafs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.JAFS
     *
     * @param jafs the value for PUB_AJ_JB.JAFS
     *
     * @mbggenerated
     */
    public void setJafs(String jafs) {
        this.jafs = jafs == null ? null : jafs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.JAYY
     *
     * @return the value of PUB_AJ_JB.JAYY
     *
     * @mbggenerated
     */
    public String getJayy() {
        return jayy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.JAYY
     *
     * @param jayy the value for PUB_AJ_JB.JAYY
     *
     * @mbggenerated
     */
    public void setJayy(String jayy) {
        this.jayy = jayy == null ? null : jayy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.JAYYDM
     *
     * @return the value of PUB_AJ_JB.JAYYDM
     *
     * @mbggenerated
     */
    public String getJayydm() {
        return jayydm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.JAYYDM
     *
     * @param jayydm the value for PUB_AJ_JB.JAYYDM
     *
     * @mbggenerated
     */
    public void setJayydm(String jayydm) {
        this.jayydm = jayydm == null ? null : jayydm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.BZ
     *
     * @return the value of PUB_AJ_JB.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.BZ
     *
     * @param bz the value for PUB_AJ_JB.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SXRQ
     *
     * @return the value of PUB_AJ_JB.SXRQ
     *
     * @mbggenerated
     */
    public Date getSxrq() {
        return sxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SXRQ
     *
     * @param sxrq the value for PUB_AJ_JB.SXRQ
     *
     * @mbggenerated
     */
    public void setSxrq(Date sxrq) {
        this.sxrq = sxrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.GDBZ
     *
     * @return the value of PUB_AJ_JB.GDBZ
     *
     * @mbggenerated
     */
    public String getGdbz() {
        return gdbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.GDBZ
     *
     * @param gdbz the value for PUB_AJ_JB.GDBZ
     *
     * @mbggenerated
     */
    public void setGdbz(String gdbz) {
        this.gdbz = gdbz == null ? null : gdbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AJZT
     *
     * @return the value of PUB_AJ_JB.AJZT
     *
     * @mbggenerated
     */
    public String getAjzt() {
        return ajzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AJZT
     *
     * @param ajzt the value for PUB_AJ_JB.AJZT
     *
     * @mbggenerated
     */
    public void setAjzt(String ajzt) {
        this.ajzt = ajzt == null ? null : ajzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.BYCXDZ
     *
     * @return the value of PUB_AJ_JB.BYCXDZ
     *
     * @mbggenerated
     */
    public String getBycxdz() {
        return bycxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.BYCXDZ
     *
     * @param bycxdz the value for PUB_AJ_JB.BYCXDZ
     *
     * @mbggenerated
     */
    public void setBycxdz(String bycxdz) {
        this.bycxdz = bycxdz == null ? null : bycxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AJWSQK
     *
     * @return the value of PUB_AJ_JB.AJWSQK
     *
     * @mbggenerated
     */
    public String getAjwsqk() {
        return ajwsqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AJWSQK
     *
     * @param ajwsqk the value for PUB_AJ_JB.AJWSQK
     *
     * @mbggenerated
     */
    public void setAjwsqk(String ajwsqk) {
        this.ajwsqk = ajwsqk == null ? null : ajwsqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.GDRQ
     *
     * @return the value of PUB_AJ_JB.GDRQ
     *
     * @mbggenerated
     */
    public Date getGdrq() {
        return gdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.GDRQ
     *
     * @param gdrq the value for PUB_AJ_JB.GDRQ
     *
     * @mbggenerated
     */
    public void setGdrq(Date gdrq) {
        this.gdrq = gdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.GDXLH
     *
     * @return the value of PUB_AJ_JB.GDXLH
     *
     * @mbggenerated
     */
    public Integer getGdxlh() {
        return gdxlh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.GDXLH
     *
     * @param gdxlh the value for PUB_AJ_JB.GDXLH
     *
     * @mbggenerated
     */
    public void setGdxlh(Integer gdxlh) {
        this.gdxlh = gdxlh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.CBRBPRQ
     *
     * @return the value of PUB_AJ_JB.CBRBPRQ
     *
     * @mbggenerated
     */
    public Date getCbrbprq() {
        return cbrbprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.CBRBPRQ
     *
     * @param cbrbprq the value for PUB_AJ_JB.CBRBPRQ
     *
     * @mbggenerated
     */
    public void setCbrbprq(Date cbrbprq) {
        this.cbrbprq = cbrbprq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.JJAR
     *
     * @return the value of PUB_AJ_JB.JJAR
     *
     * @mbggenerated
     */
    public String getJjar() {
        return jjar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.JJAR
     *
     * @param jjar the value for PUB_AJ_JB.JJAR
     *
     * @mbggenerated
     */
    public void setJjar(String jjar) {
        this.jjar = jjar == null ? null : jjar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SPZSQRQ
     *
     * @return the value of PUB_AJ_JB.SPZSQRQ
     *
     * @mbggenerated
     */
    public Date getSpzsqrq() {
        return spzsqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SPZSQRQ
     *
     * @param spzsqrq the value for PUB_AJ_JB.SPZSQRQ
     *
     * @mbggenerated
     */
    public void setSpzsqrq(Date spzsqrq) {
        this.spzsqrq = spzsqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.HYTHYRQ
     *
     * @return the value of PUB_AJ_JB.HYTHYRQ
     *
     * @mbggenerated
     */
    public Date getHythyrq() {
        return hythyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.HYTHYRQ
     *
     * @param hythyrq the value for PUB_AJ_JB.HYTHYRQ
     *
     * @mbggenerated
     */
    public void setHythyrq(Date hythyrq) {
        this.hythyrq = hythyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.TZSQRQ
     *
     * @return the value of PUB_AJ_JB.TZSQRQ
     *
     * @mbggenerated
     */
    public Date getTzsqrq() {
        return tzsqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.TZSQRQ
     *
     * @param tzsqrq the value for PUB_AJ_JB.TZSQRQ
     *
     * @mbggenerated
     */
    public void setTzsqrq(Date tzsqrq) {
        this.tzsqrq = tzsqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.YZSQRQ
     *
     * @return the value of PUB_AJ_JB.YZSQRQ
     *
     * @mbggenerated
     */
    public Date getYzsqrq() {
        return yzsqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.YZSQRQ
     *
     * @param yzsqrq the value for PUB_AJ_JB.YZSQRQ
     *
     * @mbggenerated
     */
    public void setYzsqrq(Date yzsqrq) {
        this.yzsqrq = yzsqrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SWHJDRQ
     *
     * @return the value of PUB_AJ_JB.SWHJDRQ
     *
     * @mbggenerated
     */
    public Date getSwhjdrq() {
        return swhjdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SWHJDRQ
     *
     * @param swhjdrq the value for PUB_AJ_JB.SWHJDRQ
     *
     * @mbggenerated
     */
    public void setSwhjdrq(Date swhjdrq) {
        this.swhjdrq = swhjdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.YZQFRQ
     *
     * @return the value of PUB_AJ_JB.YZQFRQ
     *
     * @mbggenerated
     */
    public Date getYzqfrq() {
        return yzqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.YZQFRQ
     *
     * @param yzqfrq the value for PUB_AJ_JB.YZQFRQ
     *
     * @mbggenerated
     */
    public void setYzqfrq(Date yzqfrq) {
        this.yzqfrq = yzqfrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SLQK
     *
     * @return the value of PUB_AJ_JB.SLQK
     *
     * @mbggenerated
     */
    public String getSlqk() {
        return slqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SLQK
     *
     * @param slqk the value for PUB_AJ_JB.SLQK
     *
     * @mbggenerated
     */
    public void setSlqk(String slqk) {
        this.slqk = slqk == null ? null : slqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SSLX
     *
     * @return the value of PUB_AJ_JB.SSLX
     *
     * @mbggenerated
     */
    public String getSslx() {
        return sslx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SSLX
     *
     * @param sslx the value for PUB_AJ_JB.SSLX
     *
     * @mbggenerated
     */
    public void setSslx(String sslx) {
        this.sslx = sslx == null ? null : sslx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFGS
     *
     * @return the value of PUB_AJ_JB.SFGS
     *
     * @mbggenerated
     */
    public String getSfgs() {
        return sfgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFGS
     *
     * @param sfgs the value for PUB_AJ_JB.SFGS
     *
     * @mbggenerated
     */
    public void setSfgs(String sfgs) {
        this.sfgs = sfgs == null ? null : sfgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.FHCSYY
     *
     * @return the value of PUB_AJ_JB.FHCSYY
     *
     * @mbggenerated
     */
    public String getFhcsyy() {
        return fhcsyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.FHCSYY
     *
     * @param fhcsyy the value for PUB_AJ_JB.FHCSYY
     *
     * @mbggenerated
     */
    public void setFhcsyy(String fhcsyy) {
        this.fhcsyy = fhcsyy == null ? null : fhcsyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.GPYY
     *
     * @return the value of PUB_AJ_JB.GPYY
     *
     * @mbggenerated
     */
    public String getGpyy() {
        return gpyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.GPYY
     *
     * @param gpyy the value for PUB_AJ_JB.GPYY
     *
     * @mbggenerated
     */
    public void setGpyy(String gpyy) {
        this.gpyy = gpyy == null ? null : gpyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFZSCQ
     *
     * @return the value of PUB_AJ_JB.SFZSCQ
     *
     * @mbggenerated
     */
    public String getSfzscq() {
        return sfzscq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFZSCQ
     *
     * @param sfzscq the value for PUB_AJ_JB.SFZSCQ
     *
     * @mbggenerated
     */
    public void setSfzscq(String sfzscq) {
        this.sfzscq = sfzscq == null ? null : sfzscq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SWLX
     *
     * @return the value of PUB_AJ_JB.SWLX
     *
     * @mbggenerated
     */
    public String getSwlx() {
        return swlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SWLX
     *
     * @param swlx the value for PUB_AJ_JB.SWLX
     *
     * @mbggenerated
     */
    public void setSwlx(String swlx) {
        this.swlx = swlx == null ? null : swlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.MODFLAG
     *
     * @return the value of PUB_AJ_JB.MODFLAG
     *
     * @mbggenerated
     */
    public String getModflag() {
        return modflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.MODFLAG
     *
     * @param modflag the value for PUB_AJ_JB.MODFLAG
     *
     * @mbggenerated
     */
    public void setModflag(String modflag) {
        this.modflag = modflag == null ? null : modflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.TRANSFLAG
     *
     * @return the value of PUB_AJ_JB.TRANSFLAG
     *
     * @mbggenerated
     */
    public String getTransflag() {
        return transflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.TRANSFLAG
     *
     * @param transflag the value for PUB_AJ_JB.TRANSFLAG
     *
     * @mbggenerated
     */
    public void setTransflag(String transflag) {
        this.transflag = transflag == null ? null : transflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SPTG
     *
     * @return the value of PUB_AJ_JB.SPTG
     *
     * @mbggenerated
     */
    public Integer getSptg() {
        return sptg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SPTG
     *
     * @param sptg the value for PUB_AJ_JB.SPTG
     *
     * @mbggenerated
     */
    public void setSptg(Integer sptg) {
        this.sptg = sptg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.PSYCY
     *
     * @return the value of PUB_AJ_JB.PSYCY
     *
     * @mbggenerated
     */
    public String getPsycy() {
        return psycy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.PSYCY
     *
     * @param psycy the value for PUB_AJ_JB.PSYCY
     *
     * @mbggenerated
     */
    public void setPsycy(String psycy) {
        this.psycy = psycy == null ? null : psycy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.MSAJTJS
     *
     * @return the value of PUB_AJ_JB.MSAJTJS
     *
     * @mbggenerated
     */
    public String getMsajtjs() {
        return msajtjs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.MSAJTJS
     *
     * @param msajtjs the value for PUB_AJ_JB.MSAJTJS
     *
     * @mbggenerated
     */
    public void setMsajtjs(String msajtjs) {
        this.msajtjs = msajtjs == null ? null : msajtjs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.MSAJTJSSS
     *
     * @return the value of PUB_AJ_JB.MSAJTJSSS
     *
     * @mbggenerated
     */
    public String getMsajtjsss() {
        return msajtjsss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.MSAJTJSSS
     *
     * @param msajtjsss the value for PUB_AJ_JB.MSAJTJSSS
     *
     * @mbggenerated
     */
    public void setMsajtjsss(String msajtjsss) {
        this.msajtjsss = msajtjsss == null ? null : msajtjsss.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SHWDFXPG
     *
     * @return the value of PUB_AJ_JB.SHWDFXPG
     *
     * @mbggenerated
     */
    public String getShwdfxpg() {
        return shwdfxpg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SHWDFXPG
     *
     * @param shwdfxpg the value for PUB_AJ_JB.SHWDFXPG
     *
     * @mbggenerated
     */
    public void setShwdfxpg(String shwdfxpg) {
        this.shwdfxpg = shwdfxpg == null ? null : shwdfxpg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFXESS
     *
     * @return the value of PUB_AJ_JB.SFXESS
     *
     * @mbggenerated
     */
    public String getSfxess() {
        return sfxess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFXESS
     *
     * @param sfxess the value for PUB_AJ_JB.SFXESS
     *
     * @mbggenerated
     */
    public void setSfxess(String sfxess) {
        this.sfxess = sfxess == null ? null : sfxess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFFCXX
     *
     * @return the value of PUB_AJ_JB.SFFCXX
     *
     * @mbggenerated
     */
    public String getSffcxx() {
        return sffcxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFFCXX
     *
     * @param sffcxx the value for PUB_AJ_JB.SFFCXX
     *
     * @mbggenerated
     */
    public void setSffcxx(String sffcxx) {
        this.sffcxx = sffcxx == null ? null : sffcxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFCQYSCS
     *
     * @return the value of PUB_AJ_JB.SFCQYSCS
     *
     * @mbggenerated
     */
    public String getSfcqyscs() {
        return sfcqyscs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFCQYSCS
     *
     * @param sfcqyscs the value for PUB_AJ_JB.SFCQYSCS
     *
     * @mbggenerated
     */
    public void setSfcqyscs(String sfcqyscs) {
        this.sfcqyscs = sfcqyscs == null ? null : sfcqyscs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.FXHJCS
     *
     * @return the value of PUB_AJ_JB.FXHJCS
     *
     * @mbggenerated
     */
    public String getFxhjcs() {
        return fxhjcs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.FXHJCS
     *
     * @param fxhjcs the value for PUB_AJ_JB.FXHJCS
     *
     * @mbggenerated
     */
    public void setFxhjcs(String fxhjcs) {
        this.fxhjcs = fxhjcs == null ? null : fxhjcs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.PJSFFDJFNR
     *
     * @return the value of PUB_AJ_JB.PJSFFDJFNR
     *
     * @mbggenerated
     */
    public String getPjsffdjfnr() {
        return pjsffdjfnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.PJSFFDJFNR
     *
     * @param pjsffdjfnr the value for PUB_AJ_JB.PJSFFDJFNR
     *
     * @mbggenerated
     */
    public void setPjsffdjfnr(String pjsffdjfnr) {
        this.pjsffdjfnr = pjsffdjfnr == null ? null : pjsffdjfnr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFDTPJ
     *
     * @return the value of PUB_AJ_JB.SFDTPJ
     *
     * @mbggenerated
     */
    public String getSfdtpj() {
        return sfdtpj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFDTPJ
     *
     * @param sfdtpj the value for PUB_AJ_JB.SFDTPJ
     *
     * @mbggenerated
     */
    public void setSfdtpj(String sfdtpj) {
        this.sfdtpj = sfdtpj == null ? null : sfdtpj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFHJ
     *
     * @return the value of PUB_AJ_JB.SFHJ
     *
     * @mbggenerated
     */
    public String getSfhj() {
        return sfhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFHJ
     *
     * @param sfhj the value for PUB_AJ_JB.SFHJ
     *
     * @mbggenerated
     */
    public void setSfhj(String sfhj) {
        this.sfhj = sfhj == null ? null : sfhj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFKTSL
     *
     * @return the value of PUB_AJ_JB.SFKTSL
     *
     * @mbggenerated
     */
    public String getSfktsl() {
        return sfktsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFKTSL
     *
     * @param sfktsl the value for PUB_AJ_JB.SFKTSL
     *
     * @mbggenerated
     */
    public void setSfktsl(String sfktsl) {
        this.sfktsl = sfktsl == null ? null : sfktsl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFTZ
     *
     * @return the value of PUB_AJ_JB.SFTZ
     *
     * @mbggenerated
     */
    public String getSftz() {
        return sftz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFTZ
     *
     * @param sftz the value for PUB_AJ_JB.SFTZ
     *
     * @mbggenerated
     */
    public void setSftz(String sftz) {
        this.sftz = sftz == null ? null : sftz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.AJSFYS
     *
     * @return the value of PUB_AJ_JB.AJSFYS
     *
     * @mbggenerated
     */
    public String getAjsfys() {
        return ajsfys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.AJSFYS
     *
     * @param ajsfys the value for PUB_AJ_JB.AJSFYS
     *
     * @mbggenerated
     */
    public void setAjsfys(String ajsfys) {
        this.ajsfys = ajsfys == null ? null : ajsfys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.RMPSYXM
     *
     * @return the value of PUB_AJ_JB.RMPSYXM
     *
     * @mbggenerated
     */
    public String getRmpsyxm() {
        return rmpsyxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.RMPSYXM
     *
     * @param rmpsyxm the value for PUB_AJ_JB.RMPSYXM
     *
     * @mbggenerated
     */
    public void setRmpsyxm(String rmpsyxm) {
        this.rmpsyxm = rmpsyxm == null ? null : rmpsyxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.RMPSYID
     *
     * @return the value of PUB_AJ_JB.RMPSYID
     *
     * @mbggenerated
     */
    public String getRmpsyid() {
        return rmpsyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.RMPSYID
     *
     * @param rmpsyid the value for PUB_AJ_JB.RMPSYID
     *
     * @mbggenerated
     */
    public void setRmpsyid(String rmpsyid) {
        this.rmpsyid = rmpsyid == null ? null : rmpsyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SFXSSC
     *
     * @return the value of PUB_AJ_JB.SFXSSC
     *
     * @mbggenerated
     */
    public String getSfxssc() {
        return sfxssc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SFXSSC
     *
     * @param sfxssc the value for PUB_AJ_JB.SFXSSC
     *
     * @mbggenerated
     */
    public void setSfxssc(String sfxssc) {
        this.sfxssc = sfxssc == null ? null : sfxssc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.LYBM
     *
     * @return the value of PUB_AJ_JB.LYBM
     *
     * @mbggenerated
     */
    public String getLybm() {
        return lybm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.LYBM
     *
     * @param lybm the value for PUB_AJ_JB.LYBM
     *
     * @mbggenerated
     */
    public void setLybm(String lybm) {
        this.lybm = lybm == null ? null : lybm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.WJAWSYY
     *
     * @return the value of PUB_AJ_JB.WJAWSYY
     *
     * @mbggenerated
     */
    public String getWjawsyy() {
        return wjawsyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.WJAWSYY
     *
     * @param wjawsyy the value for PUB_AJ_JB.WJAWSYY
     *
     * @mbggenerated
     */
    public void setWjawsyy(String wjawsyy) {
        this.wjawsyy = wjawsyy == null ? null : wjawsyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.PJJG
     *
     * @return the value of PUB_AJ_JB.PJJG
     *
     * @mbggenerated
     */
    public String getPjjg() {
        return pjjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.PJJG
     *
     * @param pjjg the value for PUB_AJ_JB.PJJG
     *
     * @mbggenerated
     */
    public void setPjjg(String pjjg) {
        this.pjjg = pjjg == null ? null : pjjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.JATHYY
     *
     * @return the value of PUB_AJ_JB.JATHYY
     *
     * @mbggenerated
     */
    public String getJathyy() {
        return jathyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.JATHYY
     *
     * @param jathyy the value for PUB_AJ_JB.JATHYY
     *
     * @mbggenerated
     */
    public void setJathyy(String jathyy) {
        this.jathyy = jathyy == null ? null : jathyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.RZRFCKCX
     *
     * @return the value of PUB_AJ_JB.RZRFCKCX
     *
     * @mbggenerated
     */
    public String getRzrfckcx() {
        return rzrfckcx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.RZRFCKCX
     *
     * @param rzrfckcx the value for PUB_AJ_JB.RZRFCKCX
     *
     * @mbggenerated
     */
    public void setRzrfckcx(String rzrfckcx) {
        this.rzrfckcx = rzrfckcx == null ? null : rzrfckcx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.JYAQ
     *
     * @return the value of PUB_AJ_JB.JYAQ
     *
     * @mbggenerated
     */
    public String getJyaq() {
        return jyaq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.JYAQ
     *
     * @param jyaq the value for PUB_AJ_JB.JYAQ
     *
     * @mbggenerated
     */
    public void setJyaq(String jyaq) {
        this.jyaq = jyaq == null ? null : jyaq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.CBRYJ
     *
     * @return the value of PUB_AJ_JB.CBRYJ
     *
     * @mbggenerated
     */
    public String getCbryj() {
        return cbryj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.CBRYJ
     *
     * @param cbryj the value for PUB_AJ_JB.CBRYJ
     *
     * @mbggenerated
     */
    public void setCbryj(String cbryj) {
        this.cbryj = cbryj == null ? null : cbryj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.HYTYJ
     *
     * @return the value of PUB_AJ_JB.HYTYJ
     *
     * @mbggenerated
     */
    public String getHytyj() {
        return hytyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.HYTYJ
     *
     * @param hytyj the value for PUB_AJ_JB.HYTYJ
     *
     * @mbggenerated
     */
    public void setHytyj(String hytyj) {
        this.hytyj = hytyj == null ? null : hytyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.TZHYJ
     *
     * @return the value of PUB_AJ_JB.TZHYJ
     *
     * @mbggenerated
     */
    public String getTzhyj() {
        return tzhyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.TZHYJ
     *
     * @param tzhyj the value for PUB_AJ_JB.TZHYJ
     *
     * @mbggenerated
     */
    public void setTzhyj(String tzhyj) {
        this.tzhyj = tzhyj == null ? null : tzhyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.YZHYJ
     *
     * @return the value of PUB_AJ_JB.YZHYJ
     *
     * @mbggenerated
     */
    public String getYzhyj() {
        return yzhyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.YZHYJ
     *
     * @param yzhyj the value for PUB_AJ_JB.YZHYJ
     *
     * @mbggenerated
     */
    public void setYzhyj(String yzhyj) {
        this.yzhyj = yzhyj == null ? null : yzhyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_AJ_JB.SWHYJ
     *
     * @return the value of PUB_AJ_JB.SWHYJ
     *
     * @mbggenerated
     */
    public String getSwhyj() {
        return swhyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_AJ_JB.SWHYJ
     *
     * @param swhyj the value for PUB_AJ_JB.SWHYJ
     *
     * @mbggenerated
     */
    public void setSwhyj(String swhyj) {
        this.swhyj = swhyj == null ? null : swhyj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_AJ_JB
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ajxh=").append(ajxh);
        sb.append(", ah=").append(ah);
        sb.append(", ajmc=").append(ajmc);
        sb.append(", ajxz=").append(ajxz);
        sb.append(", ajly=").append(ajly);
        sb.append(", spcx=").append(spcx);
        sb.append(", spcxdz=").append(spcxdz);
        sb.append(", sycx=").append(sycx);
        sb.append(", sfys=").append(sfys);
        sb.append(", sfzdaj=").append(sfzdaj);
        sb.append(", sfjbaj=").append(sfjbaj);
        sb.append(", sffhcs=").append(sffhcs);
        sb.append(", sfwdyj=").append(sfwdyj);
        sb.append(", sx=").append(sx);
        sb.append(", fjsx=").append(fjsx);
        sb.append(", lydq=").append(lydq);
        sb.append(", baspt=").append(baspt);
        sb.append(", larq=").append(larq);
        sb.append(", lar=").append(lar);
        sb.append(", bafy=").append(bafy);
        sb.append(", gksjg=").append(gksjg);
        sb.append(", jarq=").append(jarq);
        sb.append(", jafs=").append(jafs);
        sb.append(", jayy=").append(jayy);
        sb.append(", jayydm=").append(jayydm);
        sb.append(", bz=").append(bz);
        sb.append(", sxrq=").append(sxrq);
        sb.append(", gdbz=").append(gdbz);
        sb.append(", ajzt=").append(ajzt);
        sb.append(", bycxdz=").append(bycxdz);
        sb.append(", ajwsqk=").append(ajwsqk);
        sb.append(", gdrq=").append(gdrq);
        sb.append(", gdxlh=").append(gdxlh);
        sb.append(", cbrbprq=").append(cbrbprq);
        sb.append(", jjar=").append(jjar);
        sb.append(", spzsqrq=").append(spzsqrq);
        sb.append(", hythyrq=").append(hythyrq);
        sb.append(", tzsqrq=").append(tzsqrq);
        sb.append(", yzsqrq=").append(yzsqrq);
        sb.append(", swhjdrq=").append(swhjdrq);
        sb.append(", yzqfrq=").append(yzqfrq);
        sb.append(", slqk=").append(slqk);
        sb.append(", sslx=").append(sslx);
        sb.append(", sfgs=").append(sfgs);
        sb.append(", fhcsyy=").append(fhcsyy);
        sb.append(", gpyy=").append(gpyy);
        sb.append(", sfzscq=").append(sfzscq);
        sb.append(", swlx=").append(swlx);
        sb.append(", modflag=").append(modflag);
        sb.append(", transflag=").append(transflag);
        sb.append(", sptg=").append(sptg);
        sb.append(", psycy=").append(psycy);
        sb.append(", msajtjs=").append(msajtjs);
        sb.append(", msajtjsss=").append(msajtjsss);
        sb.append(", shwdfxpg=").append(shwdfxpg);
        sb.append(", sfxess=").append(sfxess);
        sb.append(", sffcxx=").append(sffcxx);
        sb.append(", sfcqyscs=").append(sfcqyscs);
        sb.append(", fxhjcs=").append(fxhjcs);
        sb.append(", pjsffdjfnr=").append(pjsffdjfnr);
        sb.append(", sfdtpj=").append(sfdtpj);
        sb.append(", sfhj=").append(sfhj);
        sb.append(", sfktsl=").append(sfktsl);
        sb.append(", sftz=").append(sftz);
        sb.append(", ajsfys=").append(ajsfys);
        sb.append(", rmpsyxm=").append(rmpsyxm);
        sb.append(", rmpsyid=").append(rmpsyid);
        sb.append(", sfxssc=").append(sfxssc);
        sb.append(", lybm=").append(lybm);
        sb.append(", wjawsyy=").append(wjawsyy);
        sb.append(", pjjg=").append(pjjg);
        sb.append(", jathyy=").append(jathyy);
        sb.append(", rzrfckcx=").append(rzrfckcx);
        sb.append(", jyaq=").append(jyaq);
        sb.append(", cbryj=").append(cbryj);
        sb.append(", hytyj=").append(hytyj);
        sb.append(", tzhyj=").append(tzhyj);
        sb.append(", yzhyj=").append(yzhyj);
        sb.append(", swhyj=").append(swhyj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}