package com.nju.sdpt.entity;

import java.io.Serializable;

public class CpxEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_CPX.CPXBH
     *
     * @mbggenerated
     */
    private Integer cpxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_CPX.CPXMC
     *
     * @mbggenerated
     */
    private String cpxmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_CPX.CPXJC
     *
     * @mbggenerated
     */
    private String cpxjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_CPX.CPXLX
     *
     * @mbggenerated
     */
    private String cpxlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_CPX.DYTJ
     *
     * @mbggenerated
     */
    private String dytj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PUB_XTGL_CPX
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_CPX.CPXBH
     *
     * @return the value of PUB_XTGL_CPX.CPXBH
     *
     * @mbggenerated
     */
    public Integer getCpxbh() {
        return cpxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_CPX.CPXBH
     *
     * @param cpxbh the value for PUB_XTGL_CPX.CPXBH
     *
     * @mbggenerated
     */
    public void setCpxbh(Integer cpxbh) {
        this.cpxbh = cpxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_CPX.CPXMC
     *
     * @return the value of PUB_XTGL_CPX.CPXMC
     *
     * @mbggenerated
     */
    public String getCpxmc() {
        return cpxmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_CPX.CPXMC
     *
     * @param cpxmc the value for PUB_XTGL_CPX.CPXMC
     *
     * @mbggenerated
     */
    public void setCpxmc(String cpxmc) {
        this.cpxmc = cpxmc == null ? null : cpxmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_CPX.CPXJC
     *
     * @return the value of PUB_XTGL_CPX.CPXJC
     *
     * @mbggenerated
     */
    public String getCpxjc() {
        return cpxjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_CPX.CPXJC
     *
     * @param cpxjc the value for PUB_XTGL_CPX.CPXJC
     *
     * @mbggenerated
     */
    public void setCpxjc(String cpxjc) {
        this.cpxjc = cpxjc == null ? null : cpxjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_CPX.CPXLX
     *
     * @return the value of PUB_XTGL_CPX.CPXLX
     *
     * @mbggenerated
     */
    public String getCpxlx() {
        return cpxlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_CPX.CPXLX
     *
     * @param cpxlx the value for PUB_XTGL_CPX.CPXLX
     *
     * @mbggenerated
     */
    public void setCpxlx(String cpxlx) {
        this.cpxlx = cpxlx == null ? null : cpxlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_CPX.DYTJ
     *
     * @return the value of PUB_XTGL_CPX.DYTJ
     *
     * @mbggenerated
     */
    public String getDytj() {
        return dytj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_CPX.DYTJ
     *
     * @param dytj the value for PUB_XTGL_CPX.DYTJ
     *
     * @mbggenerated
     */
    public void setDytj(String dytj) {
        this.dytj = dytj == null ? null : dytj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XTGL_CPX
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cpxbh=").append(cpxbh);
        sb.append(", cpxmc=").append(cpxmc);
        sb.append(", cpxjc=").append(cpxjc);
        sb.append(", cpxlx=").append(cpxlx);
        sb.append(", dytj=").append(dytj);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}