package com.nju.sdpt.entity;


import java.io.Serializable;
import java.util.Date;

public class DsrDwEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.DSRBH
     *
     * @mbggenerated
     */
    private Integer dsrbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.DWMC
     *
     * @mbggenerated
     */
    private String dwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.DZ
     *
     * @mbggenerated
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.DH
     *
     * @mbggenerated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.YB
     *
     * @mbggenerated
     */
    private String yb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.FRXZ
     *
     * @mbggenerated
     */
    private String frxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.GYQYGM
     *
     * @mbggenerated
     */
    private String gyqygm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.FDDBRXM
     *
     * @mbggenerated
     */
    private String fddbrxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.FDDBRXB
     *
     * @mbggenerated
     */
    private String fddbrxb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.CSNYR
     *
     * @mbggenerated
     */
    private Date csnyr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.WHCD
     *
     * @mbggenerated
     */
    private String whcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.ZZMM
     *
     * @mbggenerated
     */
    private String zzmm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.JB
     *
     * @mbggenerated
     */
    private String jb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.ZW
     *
     * @mbggenerated
     */
    private String zw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.LXDH
     *
     * @mbggenerated
     */
    private String lxdh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.DBRZW
     *
     * @mbggenerated
     */
    private String dbrzw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.DJZLB
     *
     * @mbggenerated
     */
    private String djzlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_DW.DJZH
     *
     * @mbggenerated
     */
    private String djzh;

    public DsrDwEntity() {
    }

    public DsrDwEntity(Integer ajxh, Integer dsrbh, String dwmc, String dz, String dh, String yb, String frxz, String gyqygm, String fddbrxm, String fddbrxb, Date csnyr, String whcd, String zzmm, String jb, String zw, String lxdh, String dbrzw, String djzlb, String djzh) {
        this.ajxh = ajxh;
        this.dsrbh = dsrbh;
        this.dwmc = dwmc;
        this.dz = dz;
        this.dh = dh;
        this.yb = yb;
        this.frxz = frxz;
        this.gyqygm = gyqygm;
        this.fddbrxm = fddbrxm;
        this.fddbrxb = fddbrxb;
        this.csnyr = csnyr;
        this.whcd = whcd;
        this.zzmm = zzmm;
        this.jb = jb;
        this.zw = zw;
        this.lxdh = lxdh;
        this.dbrzw = dbrzw;
        this.djzlb = djzlb;
        this.djzh = djzh;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSR_DW
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.AJXH
     *
     * @return the value of DSR_DW.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.AJXH
     *
     * @param ajxh the value for DSR_DW.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.DSRBH
     *
     * @return the value of DSR_DW.DSRBH
     *
     * @mbggenerated
     */
    public Integer getDsrbh() {
        return dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.DSRBH
     *
     * @param dsrbh the value for DSR_DW.DSRBH
     *
     * @mbggenerated
     */
    public void setDsrbh(Integer dsrbh) {
        this.dsrbh = dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.DWMC
     *
     * @return the value of DSR_DW.DWMC
     *
     * @mbggenerated
     */
    public String getDwmc() {
        return dwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.DWMC
     *
     * @param dwmc the value for DSR_DW.DWMC
     *
     * @mbggenerated
     */
    public void setDwmc(String dwmc) {
        this.dwmc = dwmc == null ? null : dwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.DZ
     *
     * @return the value of DSR_DW.DZ
     *
     * @mbggenerated
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.DZ
     *
     * @param dz the value for DSR_DW.DZ
     *
     * @mbggenerated
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.DH
     *
     * @return the value of DSR_DW.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.DH
     *
     * @param dh the value for DSR_DW.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.YB
     *
     * @return the value of DSR_DW.YB
     *
     * @mbggenerated
     */
    public String getYb() {
        return yb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.YB
     *
     * @param yb the value for DSR_DW.YB
     *
     * @mbggenerated
     */
    public void setYb(String yb) {
        this.yb = yb == null ? null : yb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.FRXZ
     *
     * @return the value of DSR_DW.FRXZ
     *
     * @mbggenerated
     */
    public String getFrxz() {
        return frxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.FRXZ
     *
     * @param frxz the value for DSR_DW.FRXZ
     *
     * @mbggenerated
     */
    public void setFrxz(String frxz) {
        this.frxz = frxz == null ? null : frxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.GYQYGM
     *
     * @return the value of DSR_DW.GYQYGM
     *
     * @mbggenerated
     */
    public String getGyqygm() {
        return gyqygm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.GYQYGM
     *
     * @param gyqygm the value for DSR_DW.GYQYGM
     *
     * @mbggenerated
     */
    public void setGyqygm(String gyqygm) {
        this.gyqygm = gyqygm == null ? null : gyqygm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.FDDBRXM
     *
     * @return the value of DSR_DW.FDDBRXM
     *
     * @mbggenerated
     */
    public String getFddbrxm() {
        return fddbrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.FDDBRXM
     *
     * @param fddbrxm the value for DSR_DW.FDDBRXM
     *
     * @mbggenerated
     */
    public void setFddbrxm(String fddbrxm) {
        this.fddbrxm = fddbrxm == null ? null : fddbrxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.FDDBRXB
     *
     * @return the value of DSR_DW.FDDBRXB
     *
     * @mbggenerated
     */
    public String getFddbrxb() {
        return fddbrxb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.FDDBRXB
     *
     * @param fddbrxb the value for DSR_DW.FDDBRXB
     *
     * @mbggenerated
     */
    public void setFddbrxb(String fddbrxb) {
        this.fddbrxb = fddbrxb == null ? null : fddbrxb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.CSNYR
     *
     * @return the value of DSR_DW.CSNYR
     *
     * @mbggenerated
     */
    public Date getCsnyr() {
        return csnyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.CSNYR
     *
     * @param csnyr the value for DSR_DW.CSNYR
     *
     * @mbggenerated
     */
    public void setCsnyr(Date csnyr) {
        this.csnyr = csnyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.WHCD
     *
     * @return the value of DSR_DW.WHCD
     *
     * @mbggenerated
     */
    public String getWhcd() {
        return whcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.WHCD
     *
     * @param whcd the value for DSR_DW.WHCD
     *
     * @mbggenerated
     */
    public void setWhcd(String whcd) {
        this.whcd = whcd == null ? null : whcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.ZZMM
     *
     * @return the value of DSR_DW.ZZMM
     *
     * @mbggenerated
     */
    public String getZzmm() {
        return zzmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.ZZMM
     *
     * @param zzmm the value for DSR_DW.ZZMM
     *
     * @mbggenerated
     */
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm == null ? null : zzmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.JB
     *
     * @return the value of DSR_DW.JB
     *
     * @mbggenerated
     */
    public String getJb() {
        return jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.JB
     *
     * @param jb the value for DSR_DW.JB
     *
     * @mbggenerated
     */
    public void setJb(String jb) {
        this.jb = jb == null ? null : jb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.ZW
     *
     * @return the value of DSR_DW.ZW
     *
     * @mbggenerated
     */
    public String getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.ZW
     *
     * @param zw the value for DSR_DW.ZW
     *
     * @mbggenerated
     */
    public void setZw(String zw) {
        this.zw = zw == null ? null : zw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.LXDH
     *
     * @return the value of DSR_DW.LXDH
     *
     * @mbggenerated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.LXDH
     *
     * @param lxdh the value for DSR_DW.LXDH
     *
     * @mbggenerated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.DBRZW
     *
     * @return the value of DSR_DW.DBRZW
     *
     * @mbggenerated
     */
    public String getDbrzw() {
        return dbrzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.DBRZW
     *
     * @param dbrzw the value for DSR_DW.DBRZW
     *
     * @mbggenerated
     */
    public void setDbrzw(String dbrzw) {
        this.dbrzw = dbrzw == null ? null : dbrzw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.DJZLB
     *
     * @return the value of DSR_DW.DJZLB
     *
     * @mbggenerated
     */
    public String getDjzlb() {
        return djzlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.DJZLB
     *
     * @param djzlb the value for DSR_DW.DJZLB
     *
     * @mbggenerated
     */
    public void setDjzlb(String djzlb) {
        this.djzlb = djzlb == null ? null : djzlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_DW.DJZH
     *
     * @return the value of DSR_DW.DJZH
     *
     * @mbggenerated
     */
    public String getDjzh() {
        return djzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_DW.DJZH
     *
     * @param djzh the value for DSR_DW.DJZH
     *
     * @mbggenerated
     */
    public void setDjzh(String djzh) {
        this.djzh = djzh == null ? null : djzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSR_DW
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ajxh=").append(ajxh);
        sb.append(", dsrbh=").append(dsrbh);
        sb.append(", dwmc=").append(dwmc);
        sb.append(", dz=").append(dz);
        sb.append(", dh=").append(dh);
        sb.append(", yb=").append(yb);
        sb.append(", frxz=").append(frxz);
        sb.append(", gyqygm=").append(gyqygm);
        sb.append(", fddbrxm=").append(fddbrxm);
        sb.append(", fddbrxb=").append(fddbrxb);
        sb.append(", csnyr=").append(csnyr);
        sb.append(", whcd=").append(whcd);
        sb.append(", zzmm=").append(zzmm);
        sb.append(", jb=").append(jb);
        sb.append(", zw=").append(zw);
        sb.append(", lxdh=").append(lxdh);
        sb.append(", dbrzw=").append(dbrzw);
        sb.append(", djzlb=").append(djzlb);
        sb.append(", djzh=").append(djzh);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}