package com.nju.sdpt.entity;





import java.io.Serializable;
import java.util.Date;

public class DsrGrEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.DSRBH
     *
     * @mbggenerated
     */
    private Integer dsrbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.XB
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.CSNYR
     *
     * @mbggenerated
     */
    private Date csnyr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.MZ
     *
     * @mbggenerated
     */
    private String mz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.JG
     *
     * @mbggenerated
     */
    private String jg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.ZY
     *
     * @mbggenerated
     */
    private String zy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.ZW
     *
     * @mbggenerated
     */
    private String zw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.WHCD
     *
     * @mbggenerated
     */
    private String whcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.GZDW
     *
     * @mbggenerated
     */
    private String gzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.ZZMM
     *
     * @mbggenerated
     */
    private String zzmm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.JB
     *
     * @mbggenerated
     */
    private String jb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.SF
     *
     * @mbggenerated
     */
    private String sf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.HYQK
     *
     * @mbggenerated
     */
    private String hyqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.JTQK
     *
     * @mbggenerated
     */
    private String jtqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.JKQK
     *
     * @mbggenerated
     */
    private String jkqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.SSGJ
     *
     * @mbggenerated
     */
    private String ssgj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.SFZHM
     *
     * @mbggenerated
     */
    private String sfzhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.YB
     *
     * @mbggenerated
     */
    private String yb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.DH
     *
     * @mbggenerated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.DZ
     *
     * @mbggenerated
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.QRJG
     *
     * @mbggenerated
     */
    private String qrjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.QRGC
     *
     * @mbggenerated
     */
    private String qrgc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.ZZD
     *
     * @mbggenerated
     */
    private String zzd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.ZWZY
     *
     * @mbggenerated
     */
    private String zwzy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_GR.ZJLB
     *
     * @mbggenerated
     */
    private String zjlb;




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSR_GR
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.AJXH
     *
     * @return the value of DSR_GR.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.AJXH
     *
     * @param ajxh the value for DSR_GR.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.DSRBH
     *
     * @return the value of DSR_GR.DSRBH
     *
     * @mbggenerated
     */
    public Integer getDsrbh() {
        return dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.DSRBH
     *
     * @param dsrbh the value for DSR_GR.DSRBH
     *
     * @mbggenerated
     */
    public void setDsrbh(Integer dsrbh) {
        this.dsrbh = dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.XM
     *
     * @return the value of DSR_GR.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.XM
     *
     * @param xm the value for DSR_GR.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.XB
     *
     * @return the value of DSR_GR.XB
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.XB
     *
     * @param xb the value for DSR_GR.XB
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.CSNYR
     *
     * @return the value of DSR_GR.CSNYR
     *
     * @mbggenerated
     */
    public Date getCsnyr() {
        return csnyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.CSNYR
     *
     * @param csnyr the value for DSR_GR.CSNYR
     *
     * @mbggenerated
     */
    public void setCsnyr(Date csnyr) {
        this.csnyr = csnyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.MZ
     *
     * @return the value of DSR_GR.MZ
     *
     * @mbggenerated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.MZ
     *
     * @param mz the value for DSR_GR.MZ
     *
     * @mbggenerated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.JG
     *
     * @return the value of DSR_GR.JG
     *
     * @mbggenerated
     */
    public String getJg() {
        return jg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.JG
     *
     * @param jg the value for DSR_GR.JG
     *
     * @mbggenerated
     */
    public void setJg(String jg) {
        this.jg = jg == null ? null : jg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.ZY
     *
     * @return the value of DSR_GR.ZY
     *
     * @mbggenerated
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.ZY
     *
     * @param zy the value for DSR_GR.ZY
     *
     * @mbggenerated
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.ZW
     *
     * @return the value of DSR_GR.ZW
     *
     * @mbggenerated
     */
    public String getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.ZW
     *
     * @param zw the value for DSR_GR.ZW
     *
     * @mbggenerated
     */
    public void setZw(String zw) {
        this.zw = zw == null ? null : zw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.WHCD
     *
     * @return the value of DSR_GR.WHCD
     *
     * @mbggenerated
     */
    public String getWhcd() {
        return whcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.WHCD
     *
     * @param whcd the value for DSR_GR.WHCD
     *
     * @mbggenerated
     */
    public void setWhcd(String whcd) {
        this.whcd = whcd == null ? null : whcd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.GZDW
     *
     * @return the value of DSR_GR.GZDW
     *
     * @mbggenerated
     */
    public String getGzdw() {
        return gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.GZDW
     *
     * @param gzdw the value for DSR_GR.GZDW
     *
     * @mbggenerated
     */
    public void setGzdw(String gzdw) {
        this.gzdw = gzdw == null ? null : gzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.ZZMM
     *
     * @return the value of DSR_GR.ZZMM
     *
     * @mbggenerated
     */
    public String getZzmm() {
        return zzmm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.ZZMM
     *
     * @param zzmm the value for DSR_GR.ZZMM
     *
     * @mbggenerated
     */
    public void setZzmm(String zzmm) {
        this.zzmm = zzmm == null ? null : zzmm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.JB
     *
     * @return the value of DSR_GR.JB
     *
     * @mbggenerated
     */
    public String getJb() {
        return jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.JB
     *
     * @param jb the value for DSR_GR.JB
     *
     * @mbggenerated
     */
    public void setJb(String jb) {
        this.jb = jb == null ? null : jb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.SF
     *
     * @return the value of DSR_GR.SF
     *
     * @mbggenerated
     */
    public String getSf() {
        return sf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.SF
     *
     * @param sf the value for DSR_GR.SF
     *
     * @mbggenerated
     */
    public void setSf(String sf) {
        this.sf = sf == null ? null : sf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.HYQK
     *
     * @return the value of DSR_GR.HYQK
     *
     * @mbggenerated
     */
    public String getHyqk() {
        return hyqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.HYQK
     *
     * @param hyqk the value for DSR_GR.HYQK
     *
     * @mbggenerated
     */
    public void setHyqk(String hyqk) {
        this.hyqk = hyqk == null ? null : hyqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.JTQK
     *
     * @return the value of DSR_GR.JTQK
     *
     * @mbggenerated
     */
    public String getJtqk() {
        return jtqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.JTQK
     *
     * @param jtqk the value for DSR_GR.JTQK
     *
     * @mbggenerated
     */
    public void setJtqk(String jtqk) {
        this.jtqk = jtqk == null ? null : jtqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.JKQK
     *
     * @return the value of DSR_GR.JKQK
     *
     * @mbggenerated
     */
    public String getJkqk() {
        return jkqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.JKQK
     *
     * @param jkqk the value for DSR_GR.JKQK
     *
     * @mbggenerated
     */
    public void setJkqk(String jkqk) {
        this.jkqk = jkqk == null ? null : jkqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.SSGJ
     *
     * @return the value of DSR_GR.SSGJ
     *
     * @mbggenerated
     */
    public String getSsgj() {
        return ssgj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.SSGJ
     *
     * @param ssgj the value for DSR_GR.SSGJ
     *
     * @mbggenerated
     */
    public void setSsgj(String ssgj) {
        this.ssgj = ssgj == null ? null : ssgj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.SFZHM
     *
     * @return the value of DSR_GR.SFZHM
     *
     * @mbggenerated
     */
    public String getSfzhm() {
        return sfzhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.SFZHM
     *
     * @param sfzhm the value for DSR_GR.SFZHM
     *
     * @mbggenerated
     */
    public void setSfzhm(String sfzhm) {
        this.sfzhm = sfzhm == null ? null : sfzhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.YB
     *
     * @return the value of DSR_GR.YB
     *
     * @mbggenerated
     */
    public String getYb() {
        return yb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.YB
     *
     * @param yb the value for DSR_GR.YB
     *
     * @mbggenerated
     */
    public void setYb(String yb) {
        this.yb = yb == null ? null : yb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.DH
     *
     * @return the value of DSR_GR.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.DH
     *
     * @param dh the value for DSR_GR.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.DZ
     *
     * @return the value of DSR_GR.DZ
     *
     * @mbggenerated
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.DZ
     *
     * @param dz the value for DSR_GR.DZ
     *
     * @mbggenerated
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.QRJG
     *
     * @return the value of DSR_GR.QRJG
     *
     * @mbggenerated
     */
    public String getQrjg() {
        return qrjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.QRJG
     *
     * @param qrjg the value for DSR_GR.QRJG
     *
     * @mbggenerated
     */
    public void setQrjg(String qrjg) {
        this.qrjg = qrjg == null ? null : qrjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.QRGC
     *
     * @return the value of DSR_GR.QRGC
     *
     * @mbggenerated
     */
    public String getQrgc() {
        return qrgc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.QRGC
     *
     * @param qrgc the value for DSR_GR.QRGC
     *
     * @mbggenerated
     */
    public void setQrgc(String qrgc) {
        this.qrgc = qrgc == null ? null : qrgc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.ZZD
     *
     * @return the value of DSR_GR.ZZD
     *
     * @mbggenerated
     */
    public String getZzd() {
        return zzd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.ZZD
     *
     * @param zzd the value for DSR_GR.ZZD
     *
     * @mbggenerated
     */
    public void setZzd(String zzd) {
        this.zzd = zzd == null ? null : zzd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.ZWZY
     *
     * @return the value of DSR_GR.ZWZY
     *
     * @mbggenerated
     */
    public String getZwzy() {
        return zwzy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.ZWZY
     *
     * @param zwzy the value for DSR_GR.ZWZY
     *
     * @mbggenerated
     */
    public void setZwzy(String zwzy) {
        this.zwzy = zwzy == null ? null : zwzy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_GR.ZJLB
     *
     * @return the value of DSR_GR.ZJLB
     *
     * @mbggenerated
     */
    public String getZjlb() {
        return zjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_GR.ZJLB
     *
     * @param zjlb the value for DSR_GR.ZJLB
     *
     * @mbggenerated
     */
    public void setZjlb(String zjlb) {
        this.zjlb = zjlb == null ? null : zjlb.trim();
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ajxh=").append(ajxh);
        sb.append(", dsrbh=").append(dsrbh);
        sb.append(", xm=").append(xm);
        sb.append(", xb=").append(xb);
        sb.append(", csnyr=").append(csnyr);
        sb.append(", mz=").append(mz);
        sb.append(", jg=").append(jg);
        sb.append(", zy=").append(zy);
        sb.append(", zw=").append(zw);
        sb.append(", whcd=").append(whcd);
        sb.append(", gzdw=").append(gzdw);
        sb.append(", zzmm=").append(zzmm);
        sb.append(", jb=").append(jb);
        sb.append(", sf=").append(sf);
        sb.append(", hyqk=").append(hyqk);
        sb.append(", jtqk=").append(jtqk);
        sb.append(", jkqk=").append(jkqk);
        sb.append(", ssgj=").append(ssgj);
        sb.append(", sfzhm=").append(sfzhm);
        sb.append(", yb=").append(yb);
        sb.append(", dh=").append(dh);
        sb.append(", dz=").append(dz);
        sb.append(", qrjg=").append(qrjg);
        sb.append(", qrgc=").append(qrgc);
        sb.append(", zzd=").append(zzd);
        sb.append(", zwzy=").append(zwzy);
        sb.append(", zjlb=").append(zjlb);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public DsrGrEntity(Integer ajxh, Integer dsrbh, String xm, String xb, Date csnyr, String mz, String jg, String zy, String zw, String whcd, String gzdw, String zzmm, String jb, String sf, String hyqk, String jtqk, String jkqk, String ssgj, String sfzhm, String yb, String dh, String dz, String qrjg, String qrgc, String zzd, String zwzy, String zjlb) {
        this.ajxh = ajxh;
        this.dsrbh = dsrbh;
        this.xm = xm;
        this.xb = xb;
        this.csnyr = csnyr;
        this.mz = mz;
        this.jg = jg;
        this.zy = zy;
        this.zw = zw;
        this.whcd = whcd;
        this.gzdw = gzdw;
        this.zzmm = zzmm;
        this.jb = jb;
        this.sf = sf;
        this.hyqk = hyqk;
        this.jtqk = jtqk;
        this.jkqk = jkqk;
        this.ssgj = ssgj;
        this.sfzhm = sfzhm;
        this.yb = yb;
        this.dh = dh;
        this.dz = dz;
        this.qrjg = qrjg;
        this.qrgc = qrgc;
        this.zzd = zzd;
        this.zwzy = zwzy;
        this.zjlb = zjlb;
    }

    public DsrGrEntity() {
    }
}