package com.nju.sdpt.entity;



import java.io.Serializable;

public class DsrJgEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.DSRBH
     *
     * @mbggenerated
     */
    private Integer dsrbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.JGMC
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.XZJGXZ
     *
     * @mbggenerated
     */
    private String xzjgxz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.SFFY
     *
     * @mbggenerated
     */
    private String sffy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.SFPC
     *
     * @mbggenerated
     */
    private String sfpc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.DH
     *
     * @mbggenerated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.DZ
     *
     * @mbggenerated
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.YB
     *
     * @mbggenerated
     */
    private String yb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.FDDBRXM
     *
     * @mbggenerated
     */
    private String fddbrxm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.DJZH
     *
     * @mbggenerated
     */
    private String djzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_XP_JG.DJZLB
     *
     * @mbggenerated
     */
    private String djzlb;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSR_XP_JG
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.AJXH
     *
     * @return the value of DSR_XP_JG.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.AJXH
     *
     * @param ajxh the value for DSR_XP_JG.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.DSRBH
     *
     * @return the value of DSR_XP_JG.DSRBH
     *
     * @mbggenerated
     */
    public Integer getDsrbh() {
        return dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.DSRBH
     *
     * @param dsrbh the value for DSR_XP_JG.DSRBH
     *
     * @mbggenerated
     */
    public void setDsrbh(Integer dsrbh) {
        this.dsrbh = dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.JGMC
     *
     * @return the value of DSR_XP_JG.JGMC
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.JGMC
     *
     * @param jgmc the value for DSR_XP_JG.JGMC
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.XZJGXZ
     *
     * @return the value of DSR_XP_JG.XZJGXZ
     *
     * @mbggenerated
     */
    public String getXzjgxz() {
        return xzjgxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.XZJGXZ
     *
     * @param xzjgxz the value for DSR_XP_JG.XZJGXZ
     *
     * @mbggenerated
     */
    public void setXzjgxz(String xzjgxz) {
        this.xzjgxz = xzjgxz == null ? null : xzjgxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.SFFY
     *
     * @return the value of DSR_XP_JG.SFFY
     *
     * @mbggenerated
     */
    public String getSffy() {
        return sffy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.SFFY
     *
     * @param sffy the value for DSR_XP_JG.SFFY
     *
     * @mbggenerated
     */
    public void setSffy(String sffy) {
        this.sffy = sffy == null ? null : sffy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.SFPC
     *
     * @return the value of DSR_XP_JG.SFPC
     *
     * @mbggenerated
     */
    public String getSfpc() {
        return sfpc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.SFPC
     *
     * @param sfpc the value for DSR_XP_JG.SFPC
     *
     * @mbggenerated
     */
    public void setSfpc(String sfpc) {
        this.sfpc = sfpc == null ? null : sfpc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.DH
     *
     * @return the value of DSR_XP_JG.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.DH
     *
     * @param dh the value for DSR_XP_JG.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.DZ
     *
     * @return the value of DSR_XP_JG.DZ
     *
     * @mbggenerated
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.DZ
     *
     * @param dz the value for DSR_XP_JG.DZ
     *
     * @mbggenerated
     */
    public void setDz(String dz) {
        this.dz = dz == null ? null : dz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.YB
     *
     * @return the value of DSR_XP_JG.YB
     *
     * @mbggenerated
     */
    public String getYb() {
        return yb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.YB
     *
     * @param yb the value for DSR_XP_JG.YB
     *
     * @mbggenerated
     */
    public void setYb(String yb) {
        this.yb = yb == null ? null : yb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.FDDBRXM
     *
     * @return the value of DSR_XP_JG.FDDBRXM
     *
     * @mbggenerated
     */
    public String getFddbrxm() {
        return fddbrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.FDDBRXM
     *
     * @param fddbrxm the value for DSR_XP_JG.FDDBRXM
     *
     * @mbggenerated
     */
    public void setFddbrxm(String fddbrxm) {
        this.fddbrxm = fddbrxm == null ? null : fddbrxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.DJZH
     *
     * @return the value of DSR_XP_JG.DJZH
     *
     * @mbggenerated
     */
    public String getDjzh() {
        return djzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.DJZH
     *
     * @param djzh the value for DSR_XP_JG.DJZH
     *
     * @mbggenerated
     */
    public void setDjzh(String djzh) {
        this.djzh = djzh == null ? null : djzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_XP_JG.DJZLB
     *
     * @return the value of DSR_XP_JG.DJZLB
     *
     * @mbggenerated
     */
    public String getDjzlb() {
        return djzlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_XP_JG.DJZLB
     *
     * @param djzlb the value for DSR_XP_JG.DJZLB
     *
     * @mbggenerated
     */
    public void setDjzlb(String djzlb) {
        this.djzlb = djzlb == null ? null : djzlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSR_XP_JG
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ajxh=").append(ajxh);
        sb.append(", dsrbh=").append(dsrbh);
        sb.append(", jgmc=").append(jgmc);
        sb.append(", xzjgxz=").append(xzjgxz);
        sb.append(", sffy=").append(sffy);
        sb.append(", sfpc=").append(sfpc);
        sb.append(", dh=").append(dh);
        sb.append(", dz=").append(dz);
        sb.append(", yb=").append(yb);
        sb.append(", fddbrxm=").append(fddbrxm);
        sb.append(", djzh=").append(djzh);
        sb.append(", djzlb=").append(djzlb);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    public DsrJgEntity() {
    }


    public DsrJgEntity(Integer ajxh, Integer dsrbh, String jgmc, String xzjgxz, String sffy, String sfpc, String dh, String dz, String yb, String fddbrxm, String djzh, String djzlb) {
        this.ajxh = ajxh;
        this.dsrbh = dsrbh;
        this.jgmc = jgmc;
        this.xzjgxz = xzjgxz;
        this.sffy = sffy;
        this.sfpc = sfpc;
        this.dh = dh;
        this.dz = dz;
        this.yb = yb;
        this.fddbrxm = fddbrxm;
        this.djzh = djzh;
        this.djzlb = djzlb;
    }
    public DsrJgEntity(Integer ajxh, Integer dsrbh, String jgmc, String xzjgxz, String sffy, String sfpc, String dh, String dz, String yb, String fddbrxm, String djzh, String djzlb,String fydm) {
        this.ajxh = ajxh;
        this.dsrbh = dsrbh;
        this.jgmc = jgmc;
        this.xzjgxz = xzjgxz;
        this.sffy = sffy;
        this.sfpc = sfpc;
        this.dh = dh;
        this.dz = dz;
        this.yb = yb;
        this.fddbrxm = fddbrxm;
        this.djzh = djzh;
        this.djzlb = djzlb;
    }
}