package com.nju.sdpt.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class DsrJbEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRBH
     *
     * @mbggenerated
     */
    private Integer dsrbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRSSDW
     *
     * @mbggenerated
     */
    private String dsrssdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRLB
     *
     * @mbggenerated
     */
    private String dsrlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRJC
     *
     * @mbggenerated
     */
    private String dsrjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SFSSDBR
     *
     * @mbggenerated
     */
    private String sfssdbr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRBGFS
     *
     * @mbggenerated
     */
    private String dsrbgfs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRBGYY
     *
     * @mbggenerated
     */
    private String dsrbgyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRBGSJ
     *
     * @mbggenerated
     */
    private Date dsrbgsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SFSA
     *
     * @mbggenerated
     */
    private String sfsa;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SFSG
     *
     * @mbggenerated
     */
    private String sfsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SFSQ
     *
     * @mbggenerated
     */
    private String sfsq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SFST
     *
     * @mbggenerated
     */
    private String sfst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SFSW
     *
     * @mbggenerated
     */
    private String sfsw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.QQPCJE
     *
     * @mbggenerated
     */
    private BigDecimal qqpcje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.HPJE
     *
     * @mbggenerated
     */
    private BigDecimal hpje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SFQXSP
     *
     * @mbggenerated
     */
    private String sfqxsp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.DSRQXYY
     *
     * @mbggenerated
     */
    private String dsrqxyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SSDR
     *
     * @mbggenerated
     */
    private String ssdr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SDDZ
     *
     * @mbggenerated
     */
    private String sddz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.XWNLQK
     *
     * @mbggenerated
     */
    private String xwnlqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.ZXAKZH
     *
     * @mbggenerated
     */
    private String zxakzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_JB.SCBC
     *
     * @mbggenerated
     */
    private String scbc;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DSR_JB
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.AJXH
     *
     * @return the value of DSR_JB.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.AJXH
     *
     * @param ajxh the value for DSR_JB.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRBH
     *
     * @return the value of DSR_JB.DSRBH
     *
     * @mbggenerated
     */
    public Integer getDsrbh() {
        return dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRBH
     *
     * @param dsrbh the value for DSR_JB.DSRBH
     *
     * @mbggenerated
     */
    public void setDsrbh(Integer dsrbh) {
        this.dsrbh = dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRSSDW
     *
     * @return the value of DSR_JB.DSRSSDW
     *
     * @mbggenerated
     */
    public String getDsrssdw() {
        return dsrssdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRSSDW
     *
     * @param dsrssdw the value for DSR_JB.DSRSSDW
     *
     * @mbggenerated
     */
    public void setDsrssdw(String dsrssdw) {
        this.dsrssdw = dsrssdw == null ? null : dsrssdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRLB
     *
     * @return the value of DSR_JB.DSRLB
     *
     * @mbggenerated
     */
    public String getDsrlb() {
        return dsrlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRLB
     *
     * @param dsrlb the value for DSR_JB.DSRLB
     *
     * @mbggenerated
     */
    public void setDsrlb(String dsrlb) {
        this.dsrlb = dsrlb == null ? null : dsrlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRJC
     *
     * @return the value of DSR_JB.DSRJC
     *
     * @mbggenerated
     */
    public String getDsrjc() {
        return dsrjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRJC
     *
     * @param dsrjc the value for DSR_JB.DSRJC
     *
     * @mbggenerated
     */
    public void setDsrjc(String dsrjc) {
        this.dsrjc = dsrjc == null ? null : dsrjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SFSSDBR
     *
     * @return the value of DSR_JB.SFSSDBR
     *
     * @mbggenerated
     */
    public String getSfssdbr() {
        return sfssdbr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SFSSDBR
     *
     * @param sfssdbr the value for DSR_JB.SFSSDBR
     *
     * @mbggenerated
     */
    public void setSfssdbr(String sfssdbr) {
        this.sfssdbr = sfssdbr == null ? null : sfssdbr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRBGFS
     *
     * @return the value of DSR_JB.DSRBGFS
     *
     * @mbggenerated
     */
    public String getDsrbgfs() {
        return dsrbgfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRBGFS
     *
     * @param dsrbgfs the value for DSR_JB.DSRBGFS
     *
     * @mbggenerated
     */
    public void setDsrbgfs(String dsrbgfs) {
        this.dsrbgfs = dsrbgfs == null ? null : dsrbgfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRBGYY
     *
     * @return the value of DSR_JB.DSRBGYY
     *
     * @mbggenerated
     */
    public String getDsrbgyy() {
        return dsrbgyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRBGYY
     *
     * @param dsrbgyy the value for DSR_JB.DSRBGYY
     *
     * @mbggenerated
     */
    public void setDsrbgyy(String dsrbgyy) {
        this.dsrbgyy = dsrbgyy == null ? null : dsrbgyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRBGSJ
     *
     * @return the value of DSR_JB.DSRBGSJ
     *
     * @mbggenerated
     */
    public Date getDsrbgsj() {
        return dsrbgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRBGSJ
     *
     * @param dsrbgsj the value for DSR_JB.DSRBGSJ
     *
     * @mbggenerated
     */
    public void setDsrbgsj(Date dsrbgsj) {
        this.dsrbgsj = dsrbgsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SFSA
     *
     * @return the value of DSR_JB.SFSA
     *
     * @mbggenerated
     */
    public String getSfsa() {
        return sfsa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SFSA
     *
     * @param sfsa the value for DSR_JB.SFSA
     *
     * @mbggenerated
     */
    public void setSfsa(String sfsa) {
        this.sfsa = sfsa == null ? null : sfsa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SFSG
     *
     * @return the value of DSR_JB.SFSG
     *
     * @mbggenerated
     */
    public String getSfsg() {
        return sfsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SFSG
     *
     * @param sfsg the value for DSR_JB.SFSG
     *
     * @mbggenerated
     */
    public void setSfsg(String sfsg) {
        this.sfsg = sfsg == null ? null : sfsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SFSQ
     *
     * @return the value of DSR_JB.SFSQ
     *
     * @mbggenerated
     */
    public String getSfsq() {
        return sfsq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SFSQ
     *
     * @param sfsq the value for DSR_JB.SFSQ
     *
     * @mbggenerated
     */
    public void setSfsq(String sfsq) {
        this.sfsq = sfsq == null ? null : sfsq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SFST
     *
     * @return the value of DSR_JB.SFST
     *
     * @mbggenerated
     */
    public String getSfst() {
        return sfst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SFST
     *
     * @param sfst the value for DSR_JB.SFST
     *
     * @mbggenerated
     */
    public void setSfst(String sfst) {
        this.sfst = sfst == null ? null : sfst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SFSW
     *
     * @return the value of DSR_JB.SFSW
     *
     * @mbggenerated
     */
    public String getSfsw() {
        return sfsw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SFSW
     *
     * @param sfsw the value for DSR_JB.SFSW
     *
     * @mbggenerated
     */
    public void setSfsw(String sfsw) {
        this.sfsw = sfsw == null ? null : sfsw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.QQPCJE
     *
     * @return the value of DSR_JB.QQPCJE
     *
     * @mbggenerated
     */
    public BigDecimal getQqpcje() {
        return qqpcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.QQPCJE
     *
     * @param qqpcje the value for DSR_JB.QQPCJE
     *
     * @mbggenerated
     */
    public void setQqpcje(BigDecimal qqpcje) {
        this.qqpcje = qqpcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.HPJE
     *
     * @return the value of DSR_JB.HPJE
     *
     * @mbggenerated
     */
    public BigDecimal getHpje() {
        return hpje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.HPJE
     *
     * @param hpje the value for DSR_JB.HPJE
     *
     * @mbggenerated
     */
    public void setHpje(BigDecimal hpje) {
        this.hpje = hpje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SFQXSP
     *
     * @return the value of DSR_JB.SFQXSP
     *
     * @mbggenerated
     */
    public String getSfqxsp() {
        return sfqxsp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SFQXSP
     *
     * @param sfqxsp the value for DSR_JB.SFQXSP
     *
     * @mbggenerated
     */
    public void setSfqxsp(String sfqxsp) {
        this.sfqxsp = sfqxsp == null ? null : sfqxsp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.DSRQXYY
     *
     * @return the value of DSR_JB.DSRQXYY
     *
     * @mbggenerated
     */
    public String getDsrqxyy() {
        return dsrqxyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.DSRQXYY
     *
     * @param dsrqxyy the value for DSR_JB.DSRQXYY
     *
     * @mbggenerated
     */
    public void setDsrqxyy(String dsrqxyy) {
        this.dsrqxyy = dsrqxyy == null ? null : dsrqxyy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SSDR
     *
     * @return the value of DSR_JB.SSDR
     *
     * @mbggenerated
     */
    public String getSsdr() {
        return ssdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SSDR
     *
     * @param ssdr the value for DSR_JB.SSDR
     *
     * @mbggenerated
     */
    public void setSsdr(String ssdr) {
        this.ssdr = ssdr == null ? null : ssdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SDDZ
     *
     * @return the value of DSR_JB.SDDZ
     *
     * @mbggenerated
     */
    public String getSddz() {
        return sddz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SDDZ
     *
     * @param sddz the value for DSR_JB.SDDZ
     *
     * @mbggenerated
     */
    public void setSddz(String sddz) {
        this.sddz = sddz == null ? null : sddz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.XWNLQK
     *
     * @return the value of DSR_JB.XWNLQK
     *
     * @mbggenerated
     */
    public String getXwnlqk() {
        return xwnlqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.XWNLQK
     *
     * @param xwnlqk the value for DSR_JB.XWNLQK
     *
     * @mbggenerated
     */
    public void setXwnlqk(String xwnlqk) {
        this.xwnlqk = xwnlqk == null ? null : xwnlqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.ZXAKZH
     *
     * @return the value of DSR_JB.ZXAKZH
     *
     * @mbggenerated
     */
    public String getZxakzh() {
        return zxakzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.ZXAKZH
     *
     * @param zxakzh the value for DSR_JB.ZXAKZH
     *
     * @mbggenerated
     */
    public void setZxakzh(String zxakzh) {
        this.zxakzh = zxakzh == null ? null : zxakzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_JB.SCBC
     *
     * @return the value of DSR_JB.SCBC
     *
     * @mbggenerated
     */
    public String getScbc() {
        return scbc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_JB.SCBC
     *
     * @param scbc the value for DSR_JB.SCBC
     *
     * @mbggenerated
     */
    public void setScbc(String scbc) {
        this.scbc = scbc == null ? null : scbc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSR_JB
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ajxh=").append(ajxh);
        sb.append(", dsrbh=").append(dsrbh);
        sb.append(", dsrssdw=").append(dsrssdw);
        sb.append(", dsrlb=").append(dsrlb);
        sb.append(", dsrjc=").append(dsrjc);
        sb.append(", sfssdbr=").append(sfssdbr);
        sb.append(", dsrbgfs=").append(dsrbgfs);
        sb.append(", dsrbgyy=").append(dsrbgyy);
        sb.append(", dsrbgsj=").append(dsrbgsj);
        sb.append(", sfsa=").append(sfsa);
        sb.append(", sfsg=").append(sfsg);
        sb.append(", sfsq=").append(sfsq);
        sb.append(", sfst=").append(sfst);
        sb.append(", sfsw=").append(sfsw);
        sb.append(", qqpcje=").append(qqpcje);
        sb.append(", hpje=").append(hpje);
        sb.append(", sfqxsp=").append(sfqxsp);
        sb.append(", dsrqxyy=").append(dsrqxyy);
        sb.append(", ssdr=").append(ssdr);
        sb.append(", sddz=").append(sddz);
        sb.append(", xwnlqk=").append(xwnlqk);
        sb.append(", zxakzh=").append(zxakzh);
        sb.append(", scbc=").append(scbc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}