package com.nju.sdpt.entity;

public class DsrQtsscyrGxEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_QTSSCYR_GX.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_QTSSCYR_GX.DSRBH
     *
     * @mbggenerated
     */
    private Integer dsrbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DSR_QTSSCYR_GX.QTSSCYRBH
     *
     * @mbggenerated
     */
    private Integer qtsscyrbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSR_QTSSCYR_GX
     *
     * @mbggenerated
     */
    public DsrQtsscyrGxEntity(Integer ajxh, Integer dsrbh, Integer qtsscyrbh) {
        this.ajxh = ajxh;
        this.dsrbh = dsrbh;
        this.qtsscyrbh = qtsscyrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DSR_QTSSCYR_GX
     *
     * @mbggenerated
     */
    public DsrQtsscyrGxEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_QTSSCYR_GX.AJXH
     *
     * @return the value of DSR_QTSSCYR_GX.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_QTSSCYR_GX.AJXH
     *
     * @param ajxh the value for DSR_QTSSCYR_GX.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_QTSSCYR_GX.DSRBH
     *
     * @return the value of DSR_QTSSCYR_GX.DSRBH
     *
     * @mbggenerated
     */
    public Integer getDsrbh() {
        return dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_QTSSCYR_GX.DSRBH
     *
     * @param dsrbh the value for DSR_QTSSCYR_GX.DSRBH
     *
     * @mbggenerated
     */
    public void setDsrbh(Integer dsrbh) {
        this.dsrbh = dsrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DSR_QTSSCYR_GX.QTSSCYRBH
     *
     * @return the value of DSR_QTSSCYR_GX.QTSSCYRBH
     *
     * @mbggenerated
     */
    public Integer getQtsscyrbh() {
        return qtsscyrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DSR_QTSSCYR_GX.QTSSCYRBH
     *
     * @param qtsscyrbh the value for DSR_QTSSCYR_GX.QTSSCYRBH
     *
     * @mbggenerated
     */
    public void setQtsscyrbh(Integer qtsscyrbh) {
        this.qtsscyrbh = qtsscyrbh;
    }
}