package com.nju.sdpt.entity;

public class PubBgscQzKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_BGSC_QZ.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_BGSC_QZ.DMBH
     *
     * @mbggenerated
     */
    private String dmbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_BGSC_QZ.BH
     *
     * @mbggenerated
     */
    private Integer bh;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_BGSC_QZ
     *
     * @mbggenerated
     */
    public PubBgscQzKey(Integer ajxh, String dmbh, Integer bh) {
        this.ajxh = ajxh;
        this.dmbh = dmbh;
        this.bh = bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_BGSC_QZ
     *
     * @mbggenerated
     */
    public PubBgscQzKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_BGSC_QZ.AJXH
     *
     * @return the value of PUB_BGSC_QZ.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_BGSC_QZ.AJXH
     *
     * @param ajxh the value for PUB_BGSC_QZ.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_BGSC_QZ.DMBH
     *
     * @return the value of PUB_BGSC_QZ.DMBH
     *
     * @mbggenerated
     */
    public String getDmbh() {
        return dmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_BGSC_QZ.DMBH
     *
     * @param dmbh the value for PUB_BGSC_QZ.DMBH
     *
     * @mbggenerated
     */
    public void setDmbh(String dmbh) {
        this.dmbh = dmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_BGSC_QZ.BH
     *
     * @return the value of PUB_BGSC_QZ.BH
     *
     * @mbggenerated
     */
    public Integer getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_BGSC_QZ.BH
     *
     * @param bh the value for PUB_BGSC_QZ.BH
     *
     * @mbggenerated
     */
    public void setBh(Integer bh) {
        this.bh = bh;
    }
}