package com.nju.sdpt.entity;

import java.util.Date;

public class PubQtsscyrEntity extends PubQtsscyrKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.QTSSCYRLX
     *
     * @mbggenerated
     */
    private String qtsscyrlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.YDSRGX
     *
     * @mbggenerated
     */
    private String ydsrgx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.XM
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.XB
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.CSNYR
     *
     * @mbggenerated
     */
    private Date csnyr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.WHCD
     *
     * @mbggenerated
     */
    private String whcd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.GZDW
     *
     * @mbggenerated
     */
    private String gzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.ZW
     *
     * @mbggenerated
     */
    private String zw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.ZC
     *
     * @mbggenerated
     */
    private String zc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.DH
     *
     * @mbggenerated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.YB
     *
     * @mbggenerated
     */
    private String yb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.DZ
     *
     * @mbggenerated
     */
    private String dz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.CYSJ
     *
     * @mbggenerated
     */
    private Date cysj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.SFSFYZ
     *
     * @mbggenerated
     */
    private String sfsfyz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.SFZHM
     *
     * @mbggenerated
     */
    private String sfzhm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.ZJLB
     *
     * @mbggenerated
     */
    private String zjlb;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_QTSSCYR
     *
     * @mbggenerated
     */


    public PubQtsscyrEntity(Integer ajxh, Integer qtsscyrbh, String qtsscyrlx, String ydsrgx, String xm, String xb, Date csnyr, String whcd, String gzdw, String zw, String zc, String dh, String yb, String dz, Date cysj, String sfsfyz, String sfzhm, String zjlb) {
        super(ajxh, qtsscyrbh);
        this.qtsscyrlx = qtsscyrlx;
        this.ydsrgx = ydsrgx;
        this.xm = xm;
        this.xb = xb;
        this.csnyr = csnyr;
        this.whcd = whcd;
        this.gzdw = gzdw;
        this.zw = zw;
        this.zc = zc;
        this.dh = dh;
        this.yb = yb;
        this.dz = dz;
        this.cysj = cysj;
        this.sfsfyz = sfsfyz;
        this.sfzhm = sfzhm;
        this.zjlb = zjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_QTSSCYR
     *
     * @mbggenerated
     */
    public PubQtsscyrEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.QTSSCYRLX
     *
     * @return the value of PUB_QTSSCYR.QTSSCYRLX
     *
     * @mbggenerated
     */
    public String getQtsscyrlx() {
        return qtsscyrlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.QTSSCYRLX
     *
     * @param qtsscyrlx the value for PUB_QTSSCYR.QTSSCYRLX
     *
     * @mbggenerated
     */
    public void setQtsscyrlx(String qtsscyrlx) {
        this.qtsscyrlx = qtsscyrlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.YDSRGX
     *
     * @return the value of PUB_QTSSCYR.YDSRGX
     *
     * @mbggenerated
     */
    public String getYdsrgx() {
        return ydsrgx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.YDSRGX
     *
     * @param ydsrgx the value for PUB_QTSSCYR.YDSRGX
     *
     * @mbggenerated
     */
    public void setYdsrgx(String ydsrgx) {
        this.ydsrgx = ydsrgx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.XM
     *
     * @return the value of PUB_QTSSCYR.XM
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.XM
     *
     * @param xm the value for PUB_QTSSCYR.XM
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.XB
     *
     * @return the value of PUB_QTSSCYR.XB
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.XB
     *
     * @param xb the value for PUB_QTSSCYR.XB
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.CSNYR
     *
     * @return the value of PUB_QTSSCYR.CSNYR
     *
     * @mbggenerated
     */
    public Date getCsnyr() {
        return csnyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.CSNYR
     *
     * @param csnyr the value for PUB_QTSSCYR.CSNYR
     *
     * @mbggenerated
     */
    public void setCsnyr(Date csnyr) {
        this.csnyr = csnyr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.WHCD
     *
     * @return the value of PUB_QTSSCYR.WHCD
     *
     * @mbggenerated
     */
    public String getWhcd() {
        return whcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.WHCD
     *
     * @param whcd the value for PUB_QTSSCYR.WHCD
     *
     * @mbggenerated
     */
    public void setWhcd(String whcd) {
        this.whcd = whcd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.GZDW
     *
     * @return the value of PUB_QTSSCYR.GZDW
     *
     * @mbggenerated
     */
    public String getGzdw() {
        return gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.GZDW
     *
     * @param gzdw the value for PUB_QTSSCYR.GZDW
     *
     * @mbggenerated
     */
    public void setGzdw(String gzdw) {
        this.gzdw = gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.ZW
     *
     * @return the value of PUB_QTSSCYR.ZW
     *
     * @mbggenerated
     */
    public String getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.ZW
     *
     * @param zw the value for PUB_QTSSCYR.ZW
     *
     * @mbggenerated
     */
    public void setZw(String zw) {
        this.zw = zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.ZC
     *
     * @return the value of PUB_QTSSCYR.ZC
     *
     * @mbggenerated
     */
    public String getZc() {
        return zc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.ZC
     *
     * @param zc the value for PUB_QTSSCYR.ZC
     *
     * @mbggenerated
     */
    public void setZc(String zc) {
        this.zc = zc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.DH
     *
     * @return the value of PUB_QTSSCYR.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.DH
     *
     * @param dh the value for PUB_QTSSCYR.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.YB
     *
     * @return the value of PUB_QTSSCYR.YB
     *
     * @mbggenerated
     */
    public String getYb() {
        return yb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.YB
     *
     * @param yb the value for PUB_QTSSCYR.YB
     *
     * @mbggenerated
     */
    public void setYb(String yb) {
        this.yb = yb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.DZ
     *
     * @return the value of PUB_QTSSCYR.DZ
     *
     * @mbggenerated
     */
    public String getDz() {
        return dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.DZ
     *
     * @param dz the value for PUB_QTSSCYR.DZ
     *
     * @mbggenerated
     */
    public void setDz(String dz) {
        this.dz = dz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.CYSJ
     *
     * @return the value of PUB_QTSSCYR.CYSJ
     *
     * @mbggenerated
     */
    public Date getCysj() {
        return cysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.CYSJ
     *
     * @param cysj the value for PUB_QTSSCYR.CYSJ
     *
     * @mbggenerated
     */
    public void setCysj(Date cysj) {
        this.cysj = cysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.SFSFYZ
     *
     * @return the value of PUB_QTSSCYR.SFSFYZ
     *
     * @mbggenerated
     */
    public String getSfsfyz() {
        return sfsfyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.SFSFYZ
     *
     * @param sfsfyz the value for PUB_QTSSCYR.SFSFYZ
     *
     * @mbggenerated
     */
    public void setSfsfyz(String sfsfyz) {
        this.sfsfyz = sfsfyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.SFZHM
     *
     * @return the value of PUB_QTSSCYR.SFZHM
     *
     * @mbggenerated
     */
    public String getSfzhm() {
        return sfzhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.SFZHM
     *
     * @param sfzhm the value for PUB_QTSSCYR.SFZHM
     *
     * @mbggenerated
     */
    public void setSfzhm(String sfzhm) {
        this.sfzhm = sfzhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.ZJLB
     *
     * @return the value of PUB_QTSSCYR.ZJLB
     *
     * @mbggenerated
     */
    public String getZjlb() {
        return zjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.ZJLB
     *
     * @param zjlb the value for PUB_QTSSCYR.ZJLB
     *
     * @mbggenerated
     */
    public void setZjlb(String zjlb) {
        this.zjlb = zjlb;
    }
}