package com.nju.sdpt.entity;

public class PubQtsscyrKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_QTSSCYR.QTSSCYRBH
     *
     * @mbggenerated
     */
    private Integer qtsscyrbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_QTSSCYR
     *
     * @mbggenerated
     */
    public PubQtsscyrKey(Integer ajxh, Integer qtsscyrbh) {
        this.ajxh = ajxh;
        this.qtsscyrbh = qtsscyrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_QTSSCYR
     *
     * @mbggenerated
     */
    public PubQtsscyrKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.AJXH
     *
     * @return the value of PUB_QTSSCYR.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.AJXH
     *
     * @param ajxh the value for PUB_QTSSCYR.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_QTSSCYR.QTSSCYRBH
     *
     * @return the value of PUB_QTSSCYR.QTSSCYRBH
     *
     * @mbggenerated
     */
    public Integer getQtsscyrbh() {
        return qtsscyrbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_QTSSCYR.QTSSCYRBH
     *
     * @param qtsscyrbh the value for PUB_QTSSCYR.QTSSCYRBH
     *
     * @mbggenerated
     */
    public void setQtsscyrbh(Integer qtsscyrbh) {
        this.qtsscyrbh = qtsscyrbh;
    }
}