package com.nju.sdpt.entity;

public class PubWsJbKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSJBBH
     *
     * @mbggenerated
     */
    private Integer wsjbbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WS_JB
     *
     * @mbggenerated
     */
    public PubWsJbKey(Integer ajxh, Integer wsjbbh) {
        this.ajxh = ajxh;
        this.wsjbbh = wsjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WS_JB
     *
     * @mbggenerated
     */
    public PubWsJbKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.AJXH
     *
     * @return the value of PUB_WS_JB.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.AJXH
     *
     * @param ajxh the value for PUB_WS_JB.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSJBBH
     *
     * @return the value of PUB_WS_JB.WSJBBH
     *
     * @mbggenerated
     */
    public Integer getWsjbbh() {
        return wsjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSJBBH
     *
     * @param wsjbbh the value for PUB_WS_JB.WSJBBH
     *
     * @mbggenerated
     */
    public void setWsjbbh(Integer wsjbbh) {
        this.wsjbbh = wsjbbh;
    }
}