package com.nju.sdpt.entity;

import java.util.Date;

public class PubWsJbEntity extends PubWsJbKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSLB
     *
     * @mbggenerated
     */
    private String wslb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSMC
     *
     * @mbggenerated
     */
    private String wsmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.ZFJ
     *
     * @mbggenerated
     */
    private String zfj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSLBBH
     *
     * @mbggenerated
     */
    private Integer wslbbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSBH
     *
     * @mbggenerated
     */
    private Integer wsbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSYS
     *
     * @mbggenerated
     */
    private Integer wsys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSJJ
     *
     * @mbggenerated
     */
    private String wsjj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.ZZH
     *
     * @mbggenerated
     */
    private String zzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.SCRQ
     *
     * @mbggenerated
     */
    private Date scrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSWJM
     *
     * @mbggenerated
     */
    private String wswjm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSAH
     *
     * @mbggenerated
     */
    private String wsah;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSZT
     *
     * @mbggenerated
     */
    private String wszt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.SJJZ_FLAG
     *
     * @mbggenerated
     */
    private String sjjzFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSURL
     *
     * @mbggenerated
     */
    private String wsurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.SFJAWS
     *
     * @mbggenerated
     */
    private String sfjaws;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.YMCLURL
     *
     * @mbggenerated
     */
    private String ymclurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.THYY
     *
     * @mbggenerated
     */
    private String thyy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_JB.WSNR
     *
     * @mbggenerated
     */
    private byte[] wsnr;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WS_JB
     *
     * @mbggenerated
     */
    public PubWsJbEntity(Integer ajxh, Integer wsjbbh, String wslb, String wsmc, String zfj, Integer wslbbh, Integer wsbh, Integer wsys, String wsjj, String zzh, Date scrq, String wswjm, String wsah, String wszt, String sjjzFlag, String wsurl, String sfjaws, String ymclurl, String thyy, byte[] wsnr) {
        super(ajxh, wsjbbh);
        this.wslb = wslb;
        this.wsmc = wsmc;
        this.zfj = zfj;
        this.wslbbh = wslbbh;
        this.wsbh = wsbh;
        this.wsys = wsys;
        this.wsjj = wsjj;
        this.zzh = zzh;
        this.scrq = scrq;
        this.wswjm = wswjm;
        this.wsah = wsah;
        this.wszt = wszt;
        this.sjjzFlag = sjjzFlag;
        this.wsurl = wsurl;
        this.sfjaws = sfjaws;
        this.ymclurl = ymclurl;
        this.thyy = thyy;
        this.wsnr = wsnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WS_JB
     *
     * @mbggenerated
     */
    public PubWsJbEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSLB
     *
     * @return the value of PUB_WS_JB.WSLB
     *
     * @mbggenerated
     */
    public String getWslb() {
        return wslb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSLB
     *
     * @param wslb the value for PUB_WS_JB.WSLB
     *
     * @mbggenerated
     */
    public void setWslb(String wslb) {
        this.wslb = wslb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSMC
     *
     * @return the value of PUB_WS_JB.WSMC
     *
     * @mbggenerated
     */
    public String getWsmc() {
        return wsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSMC
     *
     * @param wsmc the value for PUB_WS_JB.WSMC
     *
     * @mbggenerated
     */
    public void setWsmc(String wsmc) {
        this.wsmc = wsmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.ZFJ
     *
     * @return the value of PUB_WS_JB.ZFJ
     *
     * @mbggenerated
     */
    public String getZfj() {
        return zfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.ZFJ
     *
     * @param zfj the value for PUB_WS_JB.ZFJ
     *
     * @mbggenerated
     */
    public void setZfj(String zfj) {
        this.zfj = zfj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSLBBH
     *
     * @return the value of PUB_WS_JB.WSLBBH
     *
     * @mbggenerated
     */
    public Integer getWslbbh() {
        return wslbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSLBBH
     *
     * @param wslbbh the value for PUB_WS_JB.WSLBBH
     *
     * @mbggenerated
     */
    public void setWslbbh(Integer wslbbh) {
        this.wslbbh = wslbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSBH
     *
     * @return the value of PUB_WS_JB.WSBH
     *
     * @mbggenerated
     */
    public Integer getWsbh() {
        return wsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSBH
     *
     * @param wsbh the value for PUB_WS_JB.WSBH
     *
     * @mbggenerated
     */
    public void setWsbh(Integer wsbh) {
        this.wsbh = wsbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSYS
     *
     * @return the value of PUB_WS_JB.WSYS
     *
     * @mbggenerated
     */
    public Integer getWsys() {
        return wsys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSYS
     *
     * @param wsys the value for PUB_WS_JB.WSYS
     *
     * @mbggenerated
     */
    public void setWsys(Integer wsys) {
        this.wsys = wsys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSJJ
     *
     * @return the value of PUB_WS_JB.WSJJ
     *
     * @mbggenerated
     */
    public String getWsjj() {
        return wsjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSJJ
     *
     * @param wsjj the value for PUB_WS_JB.WSJJ
     *
     * @mbggenerated
     */
    public void setWsjj(String wsjj) {
        this.wsjj = wsjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.ZZH
     *
     * @return the value of PUB_WS_JB.ZZH
     *
     * @mbggenerated
     */
    public String getZzh() {
        return zzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.ZZH
     *
     * @param zzh the value for PUB_WS_JB.ZZH
     *
     * @mbggenerated
     */
    public void setZzh(String zzh) {
        this.zzh = zzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.SCRQ
     *
     * @return the value of PUB_WS_JB.SCRQ
     *
     * @mbggenerated
     */
    public Date getScrq() {
        return scrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.SCRQ
     *
     * @param scrq the value for PUB_WS_JB.SCRQ
     *
     * @mbggenerated
     */
    public void setScrq(Date scrq) {
        this.scrq = scrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSWJM
     *
     * @return the value of PUB_WS_JB.WSWJM
     *
     * @mbggenerated
     */
    public String getWswjm() {
        return wswjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSWJM
     *
     * @param wswjm the value for PUB_WS_JB.WSWJM
     *
     * @mbggenerated
     */
    public void setWswjm(String wswjm) {
        this.wswjm = wswjm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSAH
     *
     * @return the value of PUB_WS_JB.WSAH
     *
     * @mbggenerated
     */
    public String getWsah() {
        return wsah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSAH
     *
     * @param wsah the value for PUB_WS_JB.WSAH
     *
     * @mbggenerated
     */
    public void setWsah(String wsah) {
        this.wsah = wsah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSZT
     *
     * @return the value of PUB_WS_JB.WSZT
     *
     * @mbggenerated
     */
    public String getWszt() {
        return wszt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSZT
     *
     * @param wszt the value for PUB_WS_JB.WSZT
     *
     * @mbggenerated
     */
    public void setWszt(String wszt) {
        this.wszt = wszt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.SJJZ_FLAG
     *
     * @return the value of PUB_WS_JB.SJJZ_FLAG
     *
     * @mbggenerated
     */
    public String getSjjzFlag() {
        return sjjzFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.SJJZ_FLAG
     *
     * @param sjjzFlag the value for PUB_WS_JB.SJJZ_FLAG
     *
     * @mbggenerated
     */
    public void setSjjzFlag(String sjjzFlag) {
        this.sjjzFlag = sjjzFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSURL
     *
     * @return the value of PUB_WS_JB.WSURL
     *
     * @mbggenerated
     */
    public String getWsurl() {
        return wsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSURL
     *
     * @param wsurl the value for PUB_WS_JB.WSURL
     *
     * @mbggenerated
     */
    public void setWsurl(String wsurl) {
        this.wsurl = wsurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.SFJAWS
     *
     * @return the value of PUB_WS_JB.SFJAWS
     *
     * @mbggenerated
     */
    public String getSfjaws() {
        return sfjaws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.SFJAWS
     *
     * @param sfjaws the value for PUB_WS_JB.SFJAWS
     *
     * @mbggenerated
     */
    public void setSfjaws(String sfjaws) {
        this.sfjaws = sfjaws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.YMCLURL
     *
     * @return the value of PUB_WS_JB.YMCLURL
     *
     * @mbggenerated
     */
    public String getYmclurl() {
        return ymclurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.YMCLURL
     *
     * @param ymclurl the value for PUB_WS_JB.YMCLURL
     *
     * @mbggenerated
     */
    public void setYmclurl(String ymclurl) {
        this.ymclurl = ymclurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.THYY
     *
     * @return the value of PUB_WS_JB.THYY
     *
     * @mbggenerated
     */
    public String getThyy() {
        return thyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.THYY
     *
     * @param thyy the value for PUB_WS_JB.THYY
     *
     * @mbggenerated
     */
    public void setThyy(String thyy) {
        this.thyy = thyy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_JB.WSNR
     *
     * @return the value of PUB_WS_JB.WSNR
     *
     * @mbggenerated
     */
    public byte[] getWsnr() {
        return wsnr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_JB.WSNR
     *
     * @param wsnr the value for PUB_WS_JB.WSNR
     *
     * @mbggenerated
     */
    public void setWsnr(byte[] wsnr) {
        this.wsnr = wsnr;
    }
}