package com.nju.sdpt.entity;

import java.util.Date;

public class PubWsStampLogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.STAMP_GUID
     *
     * @mbggenerated
     */
    private String stampGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.FILE_GUID
     *
     * @mbggenerated
     */
    private String fileGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.WSJBBH
     *
     * @mbggenerated
     */
    private Integer wsjbbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.CZ
     *
     * @mbggenerated
     */
    private String cz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.CZSJ
     *
     * @mbggenerated
     */
    private Date czsj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.RESULT
     *
     * @mbggenerated
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.FILENAME
     *
     * @mbggenerated
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.BH
     *
     * @mbggenerated
     */
    private Integer bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_WS_STAMP_LOG.FILE
     *
     * @mbggenerated
     */
    private byte[] file;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WS_STAMP_LOG
     *
     * @mbggenerated
     */
    public PubWsStampLogEntity(String stampGuid, String fileGuid, Integer ajxh, Integer wsjbbh, String cz, Date czsj, String result, String bz, String filename, Integer bh, byte[] file) {
        this.stampGuid = stampGuid;
        this.fileGuid = fileGuid;
        this.ajxh = ajxh;
        this.wsjbbh = wsjbbh;
        this.cz = cz;
        this.czsj = czsj;
        this.result = result;
        this.bz = bz;
        this.filename = filename;
        this.bh = bh;
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WS_STAMP_LOG
     *
     * @mbggenerated
     */
    public PubWsStampLogEntity() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.STAMP_GUID
     *
     * @return the value of PUB_WS_STAMP_LOG.STAMP_GUID
     *
     * @mbggenerated
     */
    public String getStampGuid() {
        return stampGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.STAMP_GUID
     *
     * @param stampGuid the value for PUB_WS_STAMP_LOG.STAMP_GUID
     *
     * @mbggenerated
     */
    public void setStampGuid(String stampGuid) {
        this.stampGuid = stampGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.FILE_GUID
     *
     * @return the value of PUB_WS_STAMP_LOG.FILE_GUID
     *
     * @mbggenerated
     */
    public String getFileGuid() {
        return fileGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.FILE_GUID
     *
     * @param fileGuid the value for PUB_WS_STAMP_LOG.FILE_GUID
     *
     * @mbggenerated
     */
    public void setFileGuid(String fileGuid) {
        this.fileGuid = fileGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.AJXH
     *
     * @return the value of PUB_WS_STAMP_LOG.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.AJXH
     *
     * @param ajxh the value for PUB_WS_STAMP_LOG.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.WSJBBH
     *
     * @return the value of PUB_WS_STAMP_LOG.WSJBBH
     *
     * @mbggenerated
     */
    public Integer getWsjbbh() {
        return wsjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.WSJBBH
     *
     * @param wsjbbh the value for PUB_WS_STAMP_LOG.WSJBBH
     *
     * @mbggenerated
     */
    public void setWsjbbh(Integer wsjbbh) {
        this.wsjbbh = wsjbbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.CZ
     *
     * @return the value of PUB_WS_STAMP_LOG.CZ
     *
     * @mbggenerated
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.CZ
     *
     * @param cz the value for PUB_WS_STAMP_LOG.CZ
     *
     * @mbggenerated
     */
    public void setCz(String cz) {
        this.cz = cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.CZSJ
     *
     * @return the value of PUB_WS_STAMP_LOG.CZSJ
     *
     * @mbggenerated
     */
    public Date getCzsj() {
        return czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.CZSJ
     *
     * @param czsj the value for PUB_WS_STAMP_LOG.CZSJ
     *
     * @mbggenerated
     */
    public void setCzsj(Date czsj) {
        this.czsj = czsj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.RESULT
     *
     * @return the value of PUB_WS_STAMP_LOG.RESULT
     *
     * @mbggenerated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.RESULT
     *
     * @param result the value for PUB_WS_STAMP_LOG.RESULT
     *
     * @mbggenerated
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.BZ
     *
     * @return the value of PUB_WS_STAMP_LOG.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.BZ
     *
     * @param bz the value for PUB_WS_STAMP_LOG.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.FILENAME
     *
     * @return the value of PUB_WS_STAMP_LOG.FILENAME
     *
     * @mbggenerated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.FILENAME
     *
     * @param filename the value for PUB_WS_STAMP_LOG.FILENAME
     *
     * @mbggenerated
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.BH
     *
     * @return the value of PUB_WS_STAMP_LOG.BH
     *
     * @mbggenerated
     */
    public Integer getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.BH
     *
     * @param bh the value for PUB_WS_STAMP_LOG.BH
     *
     * @mbggenerated
     */
    public void setBh(Integer bh) {
        this.bh = bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_WS_STAMP_LOG.FILE
     *
     * @return the value of PUB_WS_STAMP_LOG.FILE
     *
     * @mbggenerated
     */
    public byte[] getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_WS_STAMP_LOG.FILE
     *
     * @param file the value for PUB_WS_STAMP_LOG.FILE
     *
     * @mbggenerated
     */
    public void setFile(byte[] file) {
        this.file = file;
    }
}