package com.nju.sdpt.entity;



import java.io.Serializable;
import java.util.Date;

public class XtglLogEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_LOG.BH
     *
     * @mbggenerated
     */
    private Integer bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_LOG.AJXH
     *
     * @mbggenerated
     */
    private Integer ajxh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_LOG.AH
     *
     * @mbggenerated
     */
    private String ah;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_LOG.YHMC
     *
     * @mbggenerated
     */
    private String yhmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_LOG.CZ
     *
     * @mbggenerated
     */
    private String cz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_LOG.SJ
     *
     * @mbggenerated
     */
    private Date sj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_LOG.BZ
     *
     * @mbggenerated
     */
    private String bz;


    public XtglLogEntity getXtglLogEntity()
    {
        return update(new XtglLogEntity());
    }

    public XtglLogEntity update(XtglLogEntity xtglLogDO)
    {
        xtglLogDO.setYhmc(this.yhmc);
        xtglLogDO.setBh(this.bh);
        xtglLogDO.setAjxh(this.ajxh);
        xtglLogDO.setAh(this.ah);
        xtglLogDO.setCz(this.cz);
        xtglLogDO.setSj(this.sj);
        xtglLogDO.setBz(this.bz);
        return xtglLogDO;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PUB_XTGL_LOG
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_LOG.BH
     *
     * @return the value of PUB_XTGL_LOG.BH
     *
     * @mbggenerated
     */
    public Integer getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_LOG.BH
     *
     * @param bh the value for PUB_XTGL_LOG.BH
     *
     * @mbggenerated
     */
    public void setBh(Integer bh) {
        this.bh = bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_LOG.AJXH
     *
     * @return the value of PUB_XTGL_LOG.AJXH
     *
     * @mbggenerated
     */
    public Integer getAjxh() {
        return ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_LOG.AJXH
     *
     * @param ajxh the value for PUB_XTGL_LOG.AJXH
     *
     * @mbggenerated
     */
    public void setAjxh(Integer ajxh) {
        this.ajxh = ajxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_LOG.AH
     *
     * @return the value of PUB_XTGL_LOG.AH
     *
     * @mbggenerated
     */
    public String getAh() {
        return ah;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_LOG.AH
     *
     * @param ah the value for PUB_XTGL_LOG.AH
     *
     * @mbggenerated
     */
    public void setAh(String ah) {
        this.ah = ah == null ? null : ah.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_LOG.YHMC
     *
     * @return the value of PUB_XTGL_LOG.YHMC
     *
     * @mbggenerated
     */
    public String getYhmc() {
        return yhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_LOG.YHMC
     *
     * @param yhmc the value for PUB_XTGL_LOG.YHMC
     *
     * @mbggenerated
     */
    public void setYhmc(String yhmc) {
        this.yhmc = yhmc == null ? null : yhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_LOG.CZ
     *
     * @return the value of PUB_XTGL_LOG.CZ
     *
     * @mbggenerated
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_LOG.CZ
     *
     * @param cz the value for PUB_XTGL_LOG.CZ
     *
     * @mbggenerated
     */
    public void setCz(String cz) {
        this.cz = cz == null ? null : cz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_LOG.SJ
     *
     * @return the value of PUB_XTGL_LOG.SJ
     *
     * @mbggenerated
     */
    public Date getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_LOG.SJ
     *
     * @param sj the value for PUB_XTGL_LOG.SJ
     *
     * @mbggenerated
     */
    public void setSj(Date sj) {
        this.sj = sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_LOG.BZ
     *
     * @return the value of PUB_XTGL_LOG.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_LOG.BZ
     *
     * @param bz the value for PUB_XTGL_LOG.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XTGL_LOG
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bh=").append(bh);
        sb.append(", ajxh=").append(ajxh);
        sb.append(", ah=").append(ah);
        sb.append(", yhmc=").append(yhmc);
        sb.append(", cz=").append(cz);
        sb.append(", sj=").append(sj);
        sb.append(", bz=").append(bz);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}