package com.nju.sdpt.entity;

import java.io.Serializable;

public class XxxglEntity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.XXXBH
     *
     * @mbggenerated
     */
    private Integer xxxbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.FYBH
     *
     * @mbggenerated
     */
    private Integer fybh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.SZB
     *
     * @mbggenerated
     */
    private String szb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.SZL
     *
     * @mbggenerated
     */
    private String szl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.DATATYPE
     *
     * @mbggenerated
     */
    private String datatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.XXXJC
     *
     * @mbggenerated
     */
    private String xxxjc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.SJXX
     *
     * @mbggenerated
     */
    private String sjxx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUB_XTGL_XXXGL.SJXX2016
     *
     * @mbggenerated
     */
    private String sjxx2016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PUB_XTGL_XXXGL
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.XXXBH
     *
     * @return the value of PUB_XTGL_XXXGL.XXXBH
     *
     * @mbggenerated
     */
    public Integer getXxxbh() {
        return xxxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.XXXBH
     *
     * @param xxxbh the value for PUB_XTGL_XXXGL.XXXBH
     *
     * @mbggenerated
     */
    public void setXxxbh(Integer xxxbh) {
        this.xxxbh = xxxbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.FYBH
     *
     * @return the value of PUB_XTGL_XXXGL.FYBH
     *
     * @mbggenerated
     */
    public Integer getFybh() {
        return fybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.FYBH
     *
     * @param fybh the value for PUB_XTGL_XXXGL.FYBH
     *
     * @mbggenerated
     */
    public void setFybh(Integer fybh) {
        this.fybh = fybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.NAME
     *
     * @return the value of PUB_XTGL_XXXGL.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.NAME
     *
     * @param name the value for PUB_XTGL_XXXGL.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.SZB
     *
     * @return the value of PUB_XTGL_XXXGL.SZB
     *
     * @mbggenerated
     */
    public String getSzb() {
        return szb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.SZB
     *
     * @param szb the value for PUB_XTGL_XXXGL.SZB
     *
     * @mbggenerated
     */
    public void setSzb(String szb) {
        this.szb = szb == null ? null : szb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.SZL
     *
     * @return the value of PUB_XTGL_XXXGL.SZL
     *
     * @mbggenerated
     */
    public String getSzl() {
        return szl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.SZL
     *
     * @param szl the value for PUB_XTGL_XXXGL.SZL
     *
     * @mbggenerated
     */
    public void setSzl(String szl) {
        this.szl = szl == null ? null : szl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.DATATYPE
     *
     * @return the value of PUB_XTGL_XXXGL.DATATYPE
     *
     * @mbggenerated
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.DATATYPE
     *
     * @param datatype the value for PUB_XTGL_XXXGL.DATATYPE
     *
     * @mbggenerated
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype == null ? null : datatype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.XXXJC
     *
     * @return the value of PUB_XTGL_XXXGL.XXXJC
     *
     * @mbggenerated
     */
    public String getXxxjc() {
        return xxxjc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.XXXJC
     *
     * @param xxxjc the value for PUB_XTGL_XXXGL.XXXJC
     *
     * @mbggenerated
     */
    public void setXxxjc(String xxxjc) {
        this.xxxjc = xxxjc == null ? null : xxxjc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.SJXX
     *
     * @return the value of PUB_XTGL_XXXGL.SJXX
     *
     * @mbggenerated
     */
    public String getSjxx() {
        return sjxx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.SJXX
     *
     * @param sjxx the value for PUB_XTGL_XXXGL.SJXX
     *
     * @mbggenerated
     */
    public void setSjxx(String sjxx) {
        this.sjxx = sjxx == null ? null : sjxx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUB_XTGL_XXXGL.SJXX2016
     *
     * @return the value of PUB_XTGL_XXXGL.SJXX2016
     *
     * @mbggenerated
     */
    public String getSjxx2016() {
        return sjxx2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUB_XTGL_XXXGL.SJXX2016
     *
     * @param sjxx2016 the value for PUB_XTGL_XXXGL.SJXX2016
     *
     * @mbggenerated
     */
    public void setSjxx2016(String sjxx2016) {
        this.sjxx2016 = sjxx2016 == null ? null : sjxx2016.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XTGL_XXXGL
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", xxxbh=").append(xxxbh);
        sb.append(", fybh=").append(fybh);
        sb.append(", name=").append(name);
        sb.append(", szb=").append(szb);
        sb.append(", szl=").append(szl);
        sb.append(", datatype=").append(datatype);
        sb.append(", xxxjc=").append(xxxjc);
        sb.append(", sjxx=").append(sjxx);
        sb.append(", sjxx2016=").append(sjxx2016);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}