package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.HisSsdrDataInfoEntity;
import com.nju.sdpt.util.StringUtil;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectProvider;

import java.util.List;

public interface HisSsdrDataInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_SSDR_DATA_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_SSDR_DATA_INFO
     *
     * @mbggenerated
     */
    int insert(HisSsdrDataInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_SSDR_DATA_INFO
     *
     * @mbggenerated
     */
    int insertSelective(HisSsdrDataInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_SSDR_DATA_INFO
     *
     * @mbggenerated
     */
    HisSsdrDataInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_SSDR_DATA_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HisSsdrDataInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table HIS_SSDR_DATA_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HisSsdrDataInfoEntity record);

    @SelectProvider(type = HisSsdrDataInfoEntityMapper.SqlProvider.class,method = "selectByWhere")
    List<HisSsdrDataInfoEntity> selectByWhere(@Param("entityWhere") HisSsdrDataInfoEntity entityWhere);

    class SqlProvider{

        public String selectByWhere(@Param("entityWhere") HisSsdrDataInfoEntity entityWhere) {
            StringBuilder sql = new StringBuilder();
            sql.append(" select * from HIS_SSDR_DATA_INFO his where 1=1");
            if(null != entityWhere){
                if(StringUtil.isNotBlank(entityWhere.getFybh())){
                    sql.append(" and his.FYBH = '").append(entityWhere.getFybh()).append("' ");
                }
                if(null != entityWhere.getAjxh()){
                    sql.append(" and his.AJXH = ").append(entityWhere.getAjxh()).append(" ");
                }
                if(null != entityWhere.getSsdrbh()){
                    sql.append(" and his.SSDRBH = ").append(entityWhere.getSsdrbh()).append(" ");
                }
                if(StringUtil.isNotBlank(entityWhere.getSsdrmc())){
                    sql.append(" and his.SSDRMC = '").append(entityWhere.getSsdrmc()).append("' ");
                }
                if(StringUtil.isNotBlank(entityWhere.getSsdrsfzhm())){
                    sql.append(" and his.SSDRSFZHM = '").append(entityWhere.getSsdrsfzhm()).append("' ");
                }
            }
            return sql.toString();
        }
    }
}