package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubDbrwInfoEntity;
import com.nju.sdpt.entity.PubSsdrHmEntity;
import com.nju.sdpt.util.StringUtil;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.mapstruct.Mapper;
import org.springframework.jdbc.core.SqlProvider;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface PubDbrwInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int insert(PubDbrwInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PubDbrwInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    PubDbrwInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubDbrwInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DBRW_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubDbrwInfoEntity record);


    @SelectProvider(type = SqlProviderDbrw.class,method = "dbrwList")
    List<PubDbrwInfoEntity> dbrwList(@Param( "clzt") String clzt,@Param( "yhbh") Integer yhbh,@Param( "xzsdfs") String xzsdfs);

    @Select(value = "update PUB_DBRW_INFO set XZSDFSXQ = #{xq},CLZT='3' where ID = #{id}")
    Boolean updateLylqById(@Param( "xq") String xq ,@Param( "id") Integer id);
    @Select(value = "update PUB_DBRW_INFO set CLZT='3' where ID = #{id}")
    Boolean updatestatusById(@Param( "id") Integer id);

    class SqlProviderDbrw {
        public String dbrwList(@Param( "clzt") String clzt,@Param( "yhbh") Integer yhbh,@Param( "xzsdfs") String xzsdfs){
            StringBuilder sql = new StringBuilder();
            sql.append("select * from PUB_DBRW_INFO where YHBH = #{yhbh}");
            if(clzt != null && !StringUtil.equals(clzt,"0")){
                sql.append(" and CLZT = #{clzt}");
            }
            if(xzsdfs != null && !StringUtil.equals(xzsdfs,"0")){
                sql.append("and XZSDFS = #{xzsdfs}");
            }
            return sql.toString();
        }
    }
}