package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubDxmbInfoEntity;
import com.nju.sdpt.model.Paramjson;
import com.nju.sdpt.model.PubDxmbInfoModel;
import com.nju.sdpt.model.getParamjson;
import com.nju.sdpt.util.StringUtil;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Objects;

@Mapper
@Repository
public interface PubDxmbInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DXMB_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DXMB_INFO
     *
     * @mbggenerated
     */
    int insert(PubDxmbInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DXMB_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PubDxmbInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DXMB_INFO
     *
     * @mbggenerated
     */
    PubDxmbInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DXMB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubDxmbInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_DXMB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubDxmbInfoEntity record);


    @Select(value ="select * from PUB_DXMB_INFO  where FYBH= #{fybh}  ")
    List<PubDxmbInfoModel> selectDxmbList(@Param("fybh") String fybh);
    @Select(value ="select * from PUB_DXMB_INFO ")
    List<PubDxmbInfoModel> selectAllDxmbList();

//    @Select(value = "select * from PUB_DXMB_INFO where MBZT = 1 and FYBH in ('0',#{fybh})")
    @SelectProvider(type = SqlProviderDxmb.class,method = "selectEnablesList")
    List<PubDxmbInfoEntity> selectEnablesList(@Param("fybh") String fybh);

    @Select(value ="select * from PUB_DXTZ_INFO p where YYSDBH= #{yysdbh}  and SSDRBH=#{ssdrbh} and CREATETIME > all(select CREATETIME from PUB_DXTZ_INFO where YYSDBH= #{yysdbh} and TEMPLATEID= p.TEMPLATEID and SSDRBH=#{ssdrbh})")
    List<getParamjson> get_paramjson(@Param("ssdrbh") Integer ssdrbh, @Param("yysdbh") Integer yysdbh);

    class SqlProviderDxmb{
        public String selectEnablesList(@Param("fybh") String fybh){
            StringBuilder sql = new StringBuilder();

            sql.append("select * from PUB_DXMB_INFO where MBZT = 1 ");
            if(StringUtil.isBlank(fybh)){
                sql.append(" and FYBH = '0'");
            }else {
                if(Objects.equals(fybh,"-1")){
                    //如果法院编号为 -1 则显示全部法院的短信模板 不用拼接fybh
                }else {
                    //反之  只显示对应法院的模板  0代表公用模板
                    sql.append(" and FYBH in ('0','").append(fybh).append("')");
                }
            }

            return sql.toString();
        }
    }
}