package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubGroupEntity;
import com.nju.sdpt.entity.PubRwwtEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PubGroupEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_GROUP
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_GROUP
     *
     * @mbggenerated
     */
    int insert(PubGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_GROUP
     *
     * @mbggenerated
     */
    int insertSelective(PubGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_GROUP
     *
     * @mbggenerated
     */
    PubGroupEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_GROUP
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubGroupEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_GROUP
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubGroupEntity record);

    @Select(value = "select * from PUB_GROUP where GROUP_NAME = #{groupName} and FYBH = #{fybh}")
    List<PubGroupEntity> selectByGroupName(@Param("groupName") String groupName,@Param("fybh") Integer fybh);

    @Select(value = "select * from PUB_RWWT where YYSDBH = #{yysdbh}")
    List<PubRwwtEntity> selectByYysdbh(@Param("yysdbh") Integer yysdbh);
}