package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubLogEntity;
import com.nju.sdpt.entity.PubLogEntityKey;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PubLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PubLogEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_LOG
     *
     * @mbggenerated
     */
    int insert(PubLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_LOG
     *
     * @mbggenerated
     */
    int insertSelective(PubLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_LOG
     *
     * @mbggenerated
     */
    PubLogEntity selectByPrimaryKey(PubLogEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubLogEntity record);

    @Select(value = "select * from PUB_LOG where AJXH = #{ajxh} and FYBH = #{fybh} and LOGBH > 0  order by CREATTIME desc")
    List<PubLogEntity> getLogByAjxhAndFybh(@Param("ajxh") int ajxh, @Param("fybh") String fybh);

    @Select(value = "select  coalesce(max(LOGBH),0) from PUB_LOG where AJXH = #{ajxh} and FYBH = #{fybh}")
    int getSizeByAjxhAndFybh(@Param("ajxh") int ajxh,@Param("fybh") String fybh);

    @Select(value = "select * from PUB_LOG where YYSDBH = #{yysdbh} order by CREATTIME desc")
    List<PubLogEntity> selectByYysdbh(@Param("yysdbh") int yysdbh);

    @Select(value = "select * from PUB_LOG where YYSDBH = #{yysdbh}  and AJXH = #{ajxh} order by CREATTIME desc")
    List<PubLogEntity> selectCaLogByYysdbh(@Param("yysdbh") int yysdbh, @Param("ajxh")Integer ajxh);
}