package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubRepairInfoEntity;
import com.nju.sdpt.model.PubYysdSsdrModel;
import com.nju.sdpt.model.RepairHandleOldDataModel;
import com.nju.sdpt.model.RepairInfoModel;
import com.nju.sdpt.util.StringUtil;
import com.nju.sdpt.viewobject.DxtzLoadListVo;
import com.nju.sdpt.viewobject.RepairQueryVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface PubRepairInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_REPAIR_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_REPAIR_INFO
     *
     * @mbggenerated
     */
    int insert(PubRepairInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_REPAIR_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PubRepairInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_REPAIR_INFO
     *
     * @mbggenerated
     */
    PubRepairInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_REPAIR_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubRepairInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_REPAIR_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubRepairInfoEntity record);

    @SelectProvider(type = SqlProvider.class,method = "loadList")
    List<RepairInfoModel> loadList(@Param("queryVo") RepairQueryVo queryVo);

    @Select(value = "SELECT  ssdr.*,jb.YYSJ gdyysj,jb.AH ah FROM  PUB_YYSD_SSDR ssdr\n" +
            "            LEFT JOIN PUB_REPAIR_INFO reapir ON reapir.SSDRBH = ssdr.SSDRBH AND reapir.YYSDBH = ssdr.YYSDBH\n" +
            "            LEFT JOIN PUB_YYSD_JB jb ON ssdr.YYSDBH = jb.YYSDBH\n" +
            "            WHERE reapir.ID is NULL AND ssdr.REPAIRBATCHNO IS NOT NULL and jb.YYSDBH is not null and ssdr.REPAIRSTATUS is not null")
    List<RepairHandleOldDataModel> handle_old_data();

    class SqlProvider{
        public String loadList(@Param("queryVo") RepairQueryVo queryVo) {
            StringBuilder sql = new StringBuilder();
            sql.append("select repair.* from PUB_REPAIR_INFO repair" +
                    "   LEFT JOIN PUB_YYSD_JB yysd ON repair.YYSDBH = yysd.YYSDBH ");
            //条件
            sql.append(" WHERE 1=1 ");
            if(StringUtil.isNotBlank(queryVo.getGdryxm())){
                sql.append(" and yysd.GDRYXM = '"+queryVo.getGdryxm()+"'");
            }
            if(StringUtil.isNotBlank(queryVo.getRepairstatus())){
                sql.append(" and repair.REPAIRSTATUS = '").append(queryVo.getRepairstatus()).append("' ");
            }
            if(null != queryVo.getYysdbh()){
                sql.append(" and repair.YYSDBH = ").append(queryVo.getYysdbh());
            }
            if(null != queryVo.getSsdrbh()){
                sql.append(" and repair.SSDRBH = ").append(queryVo.getSsdrbh());
            }
            sql.append(" order by repair.CREATETIME desc");
            return sql.toString();
        }
    }
}