package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubWebcallSeatEntity;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface PubWebcallSeatEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WEBCALL_SEAT
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WEBCALL_SEAT
     *
     * @mbggenerated
     */
    int insert(PubWebcallSeatEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WEBCALL_SEAT
     *
     * @mbggenerated
     */
    int insertSelective(PubWebcallSeatEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WEBCALL_SEAT
     *
     * @mbggenerated
     */
    PubWebcallSeatEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WEBCALL_SEAT
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubWebcallSeatEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_WEBCALL_SEAT
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubWebcallSeatEntity record);

    @Select(value = "select  * from PUB_WEBCALL_SEAT where STATUS = 0 and TYPE = #{type} FOR UPDATE limit 1")
    PubWebcallSeatEntity selectSeat(@Param("type") String type);

    @Select(value = "update PUB_WEBCALL_SEAT set STATUS = 0 where SEATID = #{seatId}")
    void updateCallSeatBySeatId(@Param("seatId") String seatId);

    @Select(value = "update PUB_WEBCALL_SEAT set STATUS = 0 where STATUS = 1 and UPDATETIME < (now() - interval '${minutes} minutes')")
    void updateCallSeatMinutes(@Param("minutes") int minutes);
}