package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubXsmbInfoEntity;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.mapstruct.Mapper;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface PubXsmbInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XSMB_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XSMB_INFO
     *
     * @mbggenerated
     */
    int insert(PubXsmbInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XSMB_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PubXsmbInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XSMB_INFO
     *
     * @mbggenerated
     */
    PubXsmbInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XSMB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubXsmbInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_XSMB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubXsmbInfoEntity record);

    @Select("SELECT  * FROM PUB_XSMB_INFO WHERE FYBH = #{fybh} limit 1")
    PubXsmbInfoEntity selectOneByFybh(@Param("fybh") String fybh);
}