package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubYysdRyxxEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.springframework.cache.annotation.CacheEvict;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.cache.annotation.Caching;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.Map;

@Mapper
@Repository
public interface PubYysdRyxxEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_RYXX
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yhbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_RYXX
     *
     * @mbggenerated
     */
    @Caching(evict = {@CacheEvict(value="ryxxByYhbh",key = "#record.yhbh"),
            @CacheEvict(value="gdRyxx",key = "#record.yhdm")})
    int insert(PubYysdRyxxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_RYXX
     *
     * @mbggenerated
     */
    int insertSelective(PubYysdRyxxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_RYXX
     *
     * @mbggenerated
     */
    @Cacheable(value = "ryxxByYhbh",key = "#yhbh")
    PubYysdRyxxEntity selectByPrimaryKey(Integer yhbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_RYXX
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubYysdRyxxEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_RYXX
     *
     * @mbggenerated
     */
    @Caching(evict = {@CacheEvict(value="ryxxByYhbh",key = "#record.yhbh"),
            @CacheEvict(value="gdRyxx",key = "#record.yhdm")})
    int updateByPrimaryKey(PubYysdRyxxEntity record);



    @Select(value = "select * from PUB_YYSD_RYXX where FYBH =#{fybh} ")
    List<PubYysdRyxxEntity> getSdry(@Param("fybh") String fybh);


    @Select(value = "select * from PUB_YYSD_RYXX ")
    List<PubYysdRyxxEntity> getAllSdry();

//    @Select(value = "select * from PUB_YYSD_RYXX where YHDM=#{yhdm}")
    @SelectProvider(type = SqlProvider.class,method = "findByYhdm")
    @Cacheable(value = "gdRyxx",key="#yhdm")
    PubYysdRyxxEntity findByYhdm(@Param("yhdm") String yhdm);

    @Select(value = "select * from PUB_YYSD_RYXX where YHMC=#{yhmc}")
    List<PubYysdRyxxEntity> findByYhmc(@Param("yhmc") String yhmc);

    @Select(value = "select * from PUB_YYSD_RYXX where YHJS='admin' and FYBH = #{fybh}")
    List<PubYysdRyxxEntity>  findAdminByfybh(@Param("fybh") String fybh);

    @SelectProvider(type = PubYysdRyxxEntityMapper.SqlProvider.class,method = "selectByYysdbhs")
    List<Map<Integer,String>> selectByYysdbhs(@Param("yysdbhs") String yysdbhs);

    class SqlProvider {
        public String findByYhdm(@Param("yhdm") String yhdm){
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.append("select * from PUB_YYSD_RYXX where YHDM ='").append(yhdm).append("'");
            return  stringBuilder.toString();
        }
        public String selectByYysdbhs(@Param("yysdbhs") String yysdbhs){
            StringBuilder sql = new StringBuilder();
            sql.append("select JB.YYSDBH , RY.YHMC  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM where JB.YYSDBH in ( "+yysdbhs+")");
            return sql.toString();
        }
    }
}