package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubYysdWsEntity;
import com.nju.sdpt.entity.PubYysdWsEntityKey;
import lombok.Synchronized;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PubYysdWsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_WS
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(PubYysdWsEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_WS
     *
     * @mbggenerated
     */
    int insert(PubYysdWsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_WS
     *
     * @mbggenerated
     */
    int insertSelective(PubYysdWsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_WS
     *
     * @mbggenerated
     */
    PubYysdWsEntity selectByPrimaryKey(PubYysdWsEntityKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_WS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubYysdWsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_WS
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(PubYysdWsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_WS
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubYysdWsEntity record);
    /**
     * 获取该预约送达编号的文书数量
     * @param yysdbh
     * @return
     */
    @Select(value = "select count (*) from PUB_YYSD_WS where YYSDBH = #{yysdbh}")
    int getBhByyYysdbh(@Param("yysdbh") int yysdbh);

    @Select(value = "select * from PUB_YYSD_WS where YYSDBH = #{yysdbh}")
    PubYysdWsEntity[] selectByYysdbh(@Param("yysdbh") Integer yysdbh);

    @Select(value = "SELECT BH FROM PUB_YYSD_WS WHERE YYSDBH=#{yysdbh} AND SSDRBH=#{ssdrbh} AND WSLB = #{wslb}")
    Integer existsSameTypeWs(@Param("yysdbh")Integer yysdbh,@Param("ssdrbh")Integer ssdrbh,@Param("wslb")String wslb);

    @Select(value = "SELECT WSLB FROM PUB_YYSD_WS WHERE YYSDBH=#{yysdbh} GROUP BY WSLB")
    List<String> selectWslbByyysdbh(@Param("yysdbh") Integer yysdbh);

    @Select(value = "SELECT WSLB FROM PUB_YYSD_WS WHERE YYSDBH =  #{yysdbh} AND SSDRBH= #{ssdrbh} GROUP BY WSLB")
    List<String> selectWslbByyysdbhAndSrdrbh(@Param("yysdbh") Integer yysdbh,@Param("ssdrbh")Integer ssdrbh);

    @Select(value = "select * from PUB_YYSD_WS where YYSDBH = #{yysdbh} and BH=#{bh}")
    PubYysdWsEntity selectByYysdbhAndBh(@Param("yysdbh") Integer yysdbh,@Param("bh") Integer bh);

    @Update(value = "update PUB_YYSD_WS set WSNR = #{path} where YYSDBH = #{yysdbh} and BH = #{bh}")
    void saveWsPath(@Param("yysdbh") Integer yysdbh,@Param("bh") Integer bh,@Param("path") byte[] path);

    @Select(value = "select WSLB from PUB_YYSD_WS where YYSDBH = #{yysdbh} and SSDRBH=#{ssdrbh}")
    List<String> selectWslbByYysdbhAndSsdrbh(@Param("yysdbh") Integer yysdbh,@Param("ssdrbh")  Integer ssdrbh);

    @Select(value="select * from PUB_YYSD_WS where YYSDBH = #{yysdbh} and SSDRBH=#{ssdrbh}")
    List<PubYysdWsEntity> findByYysdbhAndSsdrbh(@Param("yysdbh") Integer yysdbh,@Param("ssdrbh")  Integer ssdrbh);
}