package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubYysdSsdrQtsscyrEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PubYysdSsdrQtsscyrEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR_QTSSCYR
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR_QTSSCYR
     *
     * @mbggenerated
     */
    int insert(PubYysdSsdrQtsscyrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR_QTSSCYR
     *
     * @mbggenerated
     */
    int insertSelective(PubYysdSsdrQtsscyrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR_QTSSCYR
     *
     * @mbggenerated
     */
    PubYysdSsdrQtsscyrEntity selectByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR_QTSSCYR
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubYysdSsdrQtsscyrEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_SSDR_QTSSCYR
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubYysdSsdrQtsscyrEntity record);


    @Select(value = "select * from PUB_YYSD_SSDR_QTSSCYR where YYSDBH = #{yysdbh}")
    List<PubYysdSsdrQtsscyrEntity> getByYysdbh(@Param("yysdbh") Integer yysdbh);
}