package com.nju.sdpt.mapper;


import com.nju.sdpt.entity.PubYysdJbEntity;
import com.nju.sdpt.model.GdcxModel;
import com.nju.sdpt.model.WsModel;
import com.nju.sdpt.model.YysdModel;
import com.nju.sdpt.model.report.ReportLjModel;
import com.nju.sdpt.model.report.ReportRepairModel;
import com.nju.sdpt.util.StringUtil;
import com.nju.sdpt.viewobject.ReportQueryVo;
import com.nju.sdpt.viewobject.YysdJbRyxxVO;
import org.apache.ibatis.annotations.*;
import org.springframework.stereotype.Repository;

import java.util.*;

@Mapper
@Repository
public interface PubYysdJbEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_JB
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer yysdbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_JB
     *
     * @mbggenerated
     */
    int insert(PubYysdJbEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_JB
     *
     * @mbggenerated
     */
    int insertSelective(PubYysdJbEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_JB
     *
     * @mbggenerated
     */
    PubYysdJbEntity selectByPrimaryKey(Integer yysdbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_JB
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubYysdJbEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_YYSD_JB
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubYysdJbEntity record);

    void updateGdryxm(PubYysdJbEntity record);

    void updateEmssd(int yysdbh);


    @SelectProvider(type = SqlProvider.class,method = "getAssignedRecord")
    List<PubYysdJbEntity> getAssignedRecord(@Param("start") String start,  @Param("end") String end,@Param("fybh") String fybh);

    @SelectProvider(type = SqlProvider.class,method = "getUndistributedRecord")
    List<PubYysdJbEntity> getUndistributedRecord(@Param("start") String start,@Param("end") String end,@Param("fybh") String fybh);


    /**
     * 获取未处理工单(通过用户名)
     * @return
     */
    @SelectProvider(type = SqlProvider.class,method = "getGdWclByGdryxm")
    List<PubYysdJbEntity> getGdWclByGdryxm(@Param("gdryxm") String gdryxm, @Param("way") String way,@Param("emsyysdbh") Integer emsyysdbh);

    /**
     * 获取已处理工单(通过用户名)
     * @param gdryxm
     * @param emsyysdbh
     * @return
     */
    @SelectProvider(type =SqlProvider.class,method = "getGdYclByGdryxm")
    List<PubYysdJbEntity> getGdYclByGdryxm(@Param("gdryxm") String gdryxm, @Param("way") String way,@Param("emsyysdbh") Integer emsyysdbh);

    /**
     * 填写送达成功记录
     * @param yysdbh
     * @param sdWay
     *
     */
    @SelectProvider(type =SqlProvider.class,method = "updateSdcgByKey")
    void updateSdcgByKey(@Param("yysdbh") Integer yysdbh, @Param("sdWay") String sdWay);



    /**
     * 填写送达失败记录
     * @param yysdbh
     * @param sdWay
     *
     */
    @SelectProvider(type =SqlProvider.class,method = "updateSdsbByKey")
    void updateSdsbByKey(@Param("yysdbh") Integer yysdbh, @Param("sdWay") String sdWay);

    @SelectProvider(type =SqlProvider.class,method = "getYysdListByGdryxm")
    List<YysdModel> getYysdListByGdryxm(@Param("gdryxm") String gdryxm);


    @Select(value = "select * from PUB_YYSD_WS where YYSDBH= #{yysdbh} and SSDRBH =#{ssdrbh}")
    List<WsModel> getYysdListByyysdbh(@Param("yysdbh") Integer yysdbh,@Param("ssdrbh") Integer ssdrbh);

    @SelectProvider(type =SqlProvider.class,method = "getYysdList")
    List<YysdModel> getYysdList(@Param("yysdbh") Integer yysdbh);

    /**
     * 根据法官姓名和送达结果查找送达列表
     * @param yhmc
     * @param sdjg
     * @return
     */
    @SelectProvider(type =SqlProvider.class,method = "findByCbrAndSdjg")
    List<PubYysdJbEntity> findByCbrAndSdjg(@Param("yhmc") String yhmc, @Param("sdjg") Integer sdjg,@Param("fybh") String fybh);

    /**
     * 查询正在修复中的工单
     * @return
     */
    @Select(value = "SELECT * FROM PUB_YYSD_JB JB WHERE JB.REPAIRSTATUS = 'RPBS002' AND JB.REPAIRBATCHNO IS NOT NULL ORDER BY YYSDBH")
    List<PubYysdJbEntity> selectRepairingList();

    @Update(value = "update PUB_YYSD_JB  set SDJG =#{sdjg},SDSJ = #{sdsj} where YYSDBH = #{yysdbh}")
    void uploadSdjgMain(@Param("yysdbh") Integer yysdbh, @Param("sdjg") String sdjg,@Param("sdsj") Date date);

    //获取未处理工单
    @Select(value = "select JB.AJXH as ajxh ,JB.FYBH as fybh ,JB.YYSDBH as yysdbh,JB.AH as ah ,JB.AJMC as ajmc ,JB.YYRXM as yyr, JB.YYSJ as yysj, RY.YHMC as sdymc , '未送达' as sdzt ,JB.SJHM as yyrdh,JB.SDJG as sdjg,(select count(*) from PUB_RWWT where PUB_RWWT.YYSDBH = JB.YYSDBH) as wtrws,JB.KTSJ as ktsj" +
            "  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM" +
            " where  JB.GDRYXM = #{yhmc} and JB.SDJG is NULL AND JB.DHSD is NULL AND JB.DZSD is NULL AND JB.EMSSD is NULL AND JB.GGSD is NULL AND JB.ZJSD is NULL AND JB.LYLQ is NULL AND JB.WTSD is NULL AND JB.ZHJSD is NULL AND JB.DXSD is NULL ORDER BY JB.YYSDBH")
    List<YysdModel> getWsdByGdryxm(@Param("yhmc") String yhmc);

    //获取送达中工单

    @Select(value = "select JB.AJXH as ajxh ,JB.FYBH as fybh ,JB.YYSDBH as yysdbh,JB.AH as ah ,JB.AJMC as ajmc ,JB.YYRXM as yyr, JB.YYSJ as yysj, RY.YHMC as sdymc , '送达中' as sdzt ,JB.SJHM as yyrdh,JB.SDJG as sdjg ,(select count(*) from PUB_RWWT where PUB_RWWT.YYSDBH = JB.YYSDBH) as wtrws,JB.KTSJ as ktsj" +
            "  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM" +
            " where JB.FKZT is null and  JB.GDRYXM = #{yhmc} and SDJG is NULL and NOT ( DHSD is NULL AND DZSD is NULL AND EMSSD is NULL AND GGSD is NULL AND ZJSD is NULL AND LYLQ is NULL AND WTSD is NULL AND ZHJSD is NULL AND DXSD is NULL)  ORDER BY JB.YYSDBH")
    List<YysdModel> getSdzByGdryxm(@Param("yhmc") String yhmc);


    //获取已送达工单
    @Select(value = "select JB.AJXH as ajxh ,JB.FYBH as fybh ,JB.YYSDBH as yysdbh,JB.AH as ah ,JB.AJMC as ajmc ,JB.YYRXM as yyr, JB.YYSJ as yysj, RY.YHMC as sdymc , '已送达' as sdzt ,JB.SJHM as yyrdh,JB.SDJG as sdjg ,(select count(*) from PUB_RWWT where PUB_RWWT.YYSDBH = JB.YYSDBH) as wtrws,JB.KTSJ as ktsj" +
            "  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM" +
            " where  JB.GDRYXM = #{yhmc} and SDJG is not NULL and SDJG!='X' ORDER BY JB.YYSDBH")
    List<YysdModel> getYsdByGdryxm( @Param("yhmc")String yhmc);

    @Update(value = "update PUB_YYSD_JB  set BZ = #{bz} where YYSDBH = #{yysdbh}")
    void updateBzByYysdbh(@Param("yysdbh") Integer yysdbh, @Param("bz") String bz);

    @Update(value = "update PUB_YYSD_JB  set KTSJ = #{ktsj} where AJXH = #{yysdbh}")
    void updateKtsjByYysdbh(@Param("yysdbh") Integer yysdbh, @Param("ktsj") String ajxh);


    @SelectProvider(type =SqlProvider.class,method = "updateYysdJbOfSdfk")
    void updateYysdJbOfSdfk( @Param("jbEntity") PubYysdJbEntity jbEntity);

    @SelectProvider(type =SqlProvider.class,method = "getGdcxResult")
    List<PubYysdJbEntity> getGdcxResult(@Param("gdcxModel") GdcxModel gdcxModel);

    @SelectProvider(type =SqlProvider.class,method = "getTsyysdResult")
    List<PubYysdJbEntity> getTsyysdResult(@Param("gdcxModel") GdcxModel gdcxModel);

    //获取已撤回工单
    @Select(value = "select JB.AJXH as ajxh ,JB.FYBH as fybh ,JB.YYSDBH as yysdbh,JB.AH as ah ,JB.AJMC as ajmc ,JB.YYRXM as yyr, JB.YYSJ as yysj, RY.YHMC as sdymc , '已撤回' as sdzt ,JB.SJHM as yyrdh,JB.SDJG as sdjg ,(select count(*) from PUB_RWWT where PUB_RWWT.YYSDBH = JB.YYSDBH) as wtrws,JB.KTSJ as ktsj" +
            "  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM" +
            " where  JB.GDRYXM = #{yhmc} and SDJG = 'X'  ORDER BY JB.YYSDBH")
    List<YysdModel> getYchGdryxm(String yhmc);

    //工单撤回
    @Update(value = "update PUB_YYSD_JB  set SDJG = 'X' where YYSDBH = #{yysdbh}")
    void gdWithdrawByYysdbh(Integer yysdbh);

    //获取已送达未确认工单
    @Select(value = "select JB.AJXH as ajxh ,JB.FYBH as fybh ,JB.YYSDBH as yysdbh,JB.AH as ah ,JB.AJMC as ajmc ,JB.YYRXM as yyr, JB.YYSJ as yysj, RY.YHMC as sdymc , '已送达未确认' as sdzt ,JB.SJHM as yyrdh,JB.SDJG as sdjg,(select count(*) from PUB_RWWT where PUB_RWWT.YYSDBH = JB.YYSDBH) as wtrws,JB.KTSJ as ktsj " +
            "  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM" +
            " where  JB.GDRYXM = #{yhmc} and SDJG is not NULL and SDJG!='X' AND SDJG != '' AND JB.FKZT is null ORDER BY JB.YYSDBH")
    List<YysdModel> getWqrByGdryxm(String yhmc);

    @Select(value = "select JB.AJXH as ajxh  ,JB.FYBH as fybh,JB.YYSDBH as yysdbh,JB.AH as ah ,JB.AJMC as ajmc ,JB.YYRXM as yyr, JB.YYSJ as yysj, RY.YHMC as sdymc , '已退回' as sdzt ,JB.SJHM as yyrdh,JB.SDJG as sdjg ,(select count(*) from PUB_RWWT where PUB_RWWT.YYSDBH = JB.YYSDBH) as wtrws,JB.KTSJ as ktsj" +
            "  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM" +
            " where  JB.GDRYXM = #{yhmc} AND JB.FKZT = 2 ORDER BY JB.YYSDBH")
    List<YysdModel> getBackByGdryxm(String yhmc);

    //获取已送达未确认工单
    @Select(value = "select JB.AJXH as ajxh ,JB.FYBH as fybh ,JB.YYSDBH as yysdbh,JB.AH as ah ,JB.AJMC as ajmc ,JB.YYRXM as yyr, JB.YYSJ as yysj, RY.YHMC as sdymc , '已送达已确认' as sdzt ,JB.SJHM as yyrdh,JB.SDJG as sdjg ,(select count(*) from PUB_RWWT where PUB_RWWT.YYSDBH = JB.YYSDBH) as wtrws,JB.KTSJ as ktsj" +
            "  from PUB_YYSD_JB as JB left join PUB_YYSD_RYXX as RY on JB.GDRYXM = RY.YHDM" +
            " where  JB.GDRYXM = #{yhmc} and SDJG is not NULL and SDJG!='X' AND JB.FKZT = 1 ORDER BY JB.YYSDBH")
    List<YysdModel> getYqrByGdryxm(String yhmc);

    /**
     * 查询
     * 累计推送案件+累计撤回+当日推送
     * 累计推送涉及人数+累计撤回涉及人数+当日推送涉及人数
     * 累计反馈送达成功的工单量+累计反馈送达失败的工单量
     * @param queryVo
     * @return
     */
    @SelectProvider(type =SqlProvider.class,method = "report_lj")
    List<ReportLjModel> report_lj(@Param("queryVo") ReportQueryVo queryVo);

    //更新送达状态
    @SelectProvider(type =SqlProvider.class,method = "updateStatusByWayAndYysdbh")
    void updateStatusByWayAndYysdbh(@Param("way")String way,@Param("yysdbh") int yysdbh);

    @SelectProvider(type =SqlProvider.class,method = "report_repair")
    List<ReportRepairModel> report_repair(@Param("queryVo") ReportQueryVo queryVo);

    @SelectProvider(type =SqlProvider.class,method = "lj_case")
    Integer lj_case(@Param("queryVo")ReportQueryVo queryVo);

    @SelectProvider(type =SqlProvider.class,method = "lj_suc_case")
    Integer lj_suc_case(@Param("queryVo")ReportQueryVo queryVo);

    @SelectProvider(type =SqlProvider.class,method = "lj_end_case")
    Integer lj_end_case(@Param("queryVo")ReportQueryVo queryVo);

    @SelectProvider(type =SqlProvider.class,method = "lj_dsd_case")
    Integer lj_dsd_case(@Param("queryVo")ReportQueryVo queryVo);

    @SelectProvider(type =SqlProvider.class,method = "lj_ssdr")
    List<Map<String,Integer>> lj_ssdr(@Param("queryVo")ReportQueryVo queryVo);

    @Select(value = "select * from PUB_YYSD_JB where GDRYXM = #{yhm}")
    List<PubYysdJbEntity> getGdByGdryxm(@Param("yhm") String yhm);

    @Select(value = "select YHMC from PUB_YYSD_RYXX where YHDM = #{yhm}")
    String getYhmc(@Param("yhm") String yhm);

    @Select(value = "select count(1) from ${tableName} where YYSDBH = #{yysdbh} and SDJG is null")
    Integer countUnsolvedRecord(@Param("tableName") String table,@Param("yysdbh") Integer yysdbh);

    @SelectProvider(type = SqlProvider.class, method = "getFeedbackRecord")
    List<YysdModel> getFeedbackRecord(String start, String end, String fybh);

    @SelectProvider(type = SqlProvider.class, method = "getUnFeedbackRecord")
    List<YysdModel> getUnFeedbackRecord(String start, String end, String fybh);

    class SqlProvider {
        public String lj_ssdr(@Param("queryVo") ReportQueryVo queryVo){
            StringBuilder sql = new StringBuilder();
            //totalNum 符合条件的总数
            //sucNum 成功的总数
            sql.append("select\n" +
                    "  count(0) as \"ljSddr\",\n" +
                    "  count(CASE WHEN ssdr.SDJG in (1,2) THEN 1 END ) as \"ljEndSddr\",\n" +
                    "  count(CASE WHEN ssdr.SDJG = 1 THEN 1 END )  as \"ljSucSddr\"\n" +
                    " from PUB_YYSD_SSDR ssdr\n" +
                    " LEFT JOIN PUB_YYSD_JB jb ON jb.YYSDBH = ssdr.YYSDBH\n" +
                    " where (jb.SDJG != 'X' OR jb.SDJG is null)");
            if(StringUtil.isNotBlank(queryVo.getStartTime()) && StringUtil.isNotBlank(queryVo.getEndTime())){
                sql.append(" and jb.YYSJ >= '").append(queryVo.getStartTime()).append("' and jb.YYSJ < '").append(queryVo.getEndTime()).append("'");
            }
            if(StringUtil.isNotBlank(queryVo.getTsName())) {
                sql.append(" and jb.bmmc = '").append(queryVo.getTsName()).append("'");
            }
//            if(StringUtil.isNotBlank(queryVo.getDsrDw())) {
//                sql.append("and jb.YYSDBH in (select YYSDBH from pub_yysd_ssdr where ssdrssdw = '").append(queryVo.getDsrDw()).append("')");
//            }
            if(StringUtil.isNotBlank(queryVo.getDsrDw())) {
                sql.append(" and ssdr.ssdrssdw = '").append(queryVo.getDsrDw()).append("'");
            }
            if(Objects.equals(queryVo.getSdptRy(),true)){
                //工单人员权限
                sql.append(" and (jb.GDRYXM = '").append(queryVo.getLoginYhm()).append("' OR jb.FYBH in ('").append(StringUtil.splitJoint(queryVo.getFybhSet(),"','")).append("') )");
            }else {
                //法官权限
                Integer authority = queryVo.getAuthority();
                sql.append(" and ( " +
                        "jb.FYBH in ('").append(StringUtil.splitJoint(queryVo.getFybhSet(),"','")).append("') ");
                if(Objects.equals(3,authority) || Objects.equals(4,authority)){
                    //部门权限
                    sql.append(" and jb.BMBH = '").append(queryVo.getBmbh()).append("'");
                }
                if(Objects.equals(4,authority)){
                    sql.append(" and jb.YYRXM = '").append(queryVo.getFgmc()).append("'");
                }
                sql.append(" ) ");
            }
            System.out.println("受送达人------------------------");
            System.out.print(sql.toString());
            return sql.toString();
        }
        public String lj_suc_case(@Param("queryVo") ReportQueryVo queryVo){
            return loadLjCaseSql(queryVo,"SUC");
        }
        public String loadLjCaseSql(ReportQueryVo queryVo,String type){
            if(queryVo.getGdOrAhType().equals("AJ")) {
                StringBuilder sql = new StringBuilder();
                sql.append("SELECT count(distinct A) 累计收案\n" +
                        "  FROM\n" +
                        "  (\n" +
                        "    SELECT\n" +
                        "      AJXH || FYBH as A,\n" +
                        "      FYBH\n" +
                        "    FROM\n" +
                        "      (\n" +
                        "        SELECT\n" +
                        "          (CASE WHEN AJXH < 0 THEN caxx_AJXH ELSE AJXH END) AJXH,\n" +
                        "          FYBH\n" +
                        "        FROM (\n" +
                        "               SELECT\n" +
                        "                 jb.AJXH,\n" +
                        "                 jb.FYBH,\n" +
                        "                caxx.AJXH caxx_AJXH\n" +
                        "               FROM PUB_YYSD_JB jb\n" +
                        "               LEFT JOIN PUB_CAXX caxx ON jb.YYSDBH = caxx.YYSDBH\n"
                );
                if(Objects.equals(type,"SUC")){
                    sql.append("WHERE jb.SDJG = 'Y' \n");
                }else if(Objects.equals(type,"END")){
                    sql.append("WHERE jb.SDJG in ('Y','N') \n");
                }else if(Objects.equals(type, "ALL")){
                    sql.append("WHERE (jb.SDJG != 'X' or jb.SDJG is null) \n");
                } else if(Objects.equals(type, "DSD")) {
                    sql.append("WHERE (jb.SDJG is NULL AND jb.DHSD is NULL AND jb.DZSD is NULL AND jb.EMSSD is NULL AND jb.GGSD is NULL AND jb.ZJSD is NULL AND jb.LYLQ is NULL AND jb.WTSD is NULL AND jb.ZHJSD is NULL AND jb.DXSD is NULL)  ");
                }
                if(Objects.equals(queryVo.getSdptRy(),true)){
                    //工单人员权限
                    sql.append(" and (jb.GDRYXM = '").append(queryVo.getLoginYhm()).append("' OR jb.FYBH in ('").append(StringUtil.splitJoint(queryVo.getFybhSet(),"','")).append("') )");
                }else {
                    //法官权限
                    Integer authority = queryVo.getAuthority();
                    sql.append(" and ( " +
                            "jb.FYBH in ('").append(StringUtil.splitJoint(queryVo.getFybhSet(),"','")).append("') ");
                    if(Objects.equals(3,authority) || Objects.equals(4,authority)){
                        //部门权限
                        sql.append(" and jb.BMBH = '").append(queryVo.getBmbh()).append("'");
                    }
                    if(Objects.equals(4,authority)){
                        sql.append(" and jb.YYRXM = '").append(queryVo.getFgmc()).append("'");
                    }
                    sql.append(" ) ");
                }
                if(StringUtil.isNotBlank(queryVo.getStartTime()) && StringUtil.isNotBlank(queryVo.getEndTime())){
                    sql.append(" and jb.YYSJ >= '").append(queryVo.getStartTime()).append("' and jb.YYSJ < '").append(queryVo.getEndTime()).append("'");
                }
                if(StringUtil.isNotBlank(queryVo.getTsName())) {
                    sql.append(" and jb.bmmc = '").append(queryVo.getTsName()).append("'");
                }
                if(StringUtil.isNotBlank(queryVo.getDsrDw())) {
                    sql.append("and jb.YYSDBH in (select YYSDBH from pub_yysd_ssdr where ssdrssdw = '").append(queryVo.getDsrDw()).append("')");
                }


                sql.append("             ) a"+
                        "      ) tmp  GROUP BY AJXH, FYBH\n" +
                        "  )tmpMain");
                System.out.println("收案------------------------");
                System.out.print(sql.toString());
                return sql.toString();
            } else {
                StringBuilder sql = new StringBuilder();
                sql.append("SELECT count(*) 累计收案\n" +
                        "  FROM\n" +
                        "  (\n" +
                        "    SELECT\n" +
                        "      YYSDBH\n" +
                        "    FROM\n" +
                        "      (\n" +
                        "        SELECT\n" +
                        "          YYSDBH\n" +
                        "        FROM (\n" +
                        "               SELECT\n" +
                        "                 jb.YYSDBH\n" +
                        "               FROM PUB_YYSD_JB jb\n"
                );
                if(Objects.equals(type,"SUC")){
                    sql.append("WHERE jb.SDJG = 'Y' \n");
                }else if(Objects.equals(type,"END")){
                    sql.append("WHERE jb.SDJG in ('Y','N') \n");
                }else if(Objects.equals(type, "ALL")){
                    sql.append("WHERE (jb.SDJG != 'X' or jb.SDJG is null) \n");
                } else if(Objects.equals(type, "DSD")) {
                    sql.append("WHERE (jb.SDJG is NULL AND jb.DHSD is NULL AND jb.DZSD is NULL AND jb.EMSSD is NULL AND jb.GGSD is NULL AND jb.ZJSD is NULL AND jb.LYLQ is NULL AND jb.WTSD is NULL AND jb.ZHJSD is NULL AND jb.DXSD is NULL)  ");
                }
                if(Objects.equals(queryVo.getSdptRy(),true)){
                    //工单人员权限
                    sql.append(" and (jb.GDRYXM = '").append(queryVo.getLoginYhm()).append("' OR jb.FYBH in ('").append(StringUtil.splitJoint(queryVo.getFybhSet(),"','")).append("') )");
                }else {
                    //法官权限
                    Integer authority = queryVo.getAuthority();
                    sql.append(" and ( " +
                            "jb.FYBH in ('").append(StringUtil.splitJoint(queryVo.getFybhSet(),"','")).append("') ");
                    if(Objects.equals(3,authority) || Objects.equals(4,authority)){
                        //部门权限
                        sql.append(" and jb.BMBH = '").append(queryVo.getBmbh()).append("'");
                    }
                    if(Objects.equals(4,authority)){
                        sql.append(" and jb.YYRXM = '").append(queryVo.getFgmc()).append("'");
                    }
                    sql.append(" ) ");
                }
                if(StringUtil.isNotBlank(queryVo.getStartTime()) && StringUtil.isNotBlank(queryVo.getEndTime())){
                    sql.append(" and jb.YYSJ >= '").append(queryVo.getStartTime()).append("' and jb.YYSJ < '").append(queryVo.getEndTime()).append("'");
                }
                if(StringUtil.isNotBlank(queryVo.getTsName())) {
                    sql.append(" and jb.bmmc = '").append(queryVo.getTsName()).append("'");
                }
                if(StringUtil.isNotBlank(queryVo.getDsrDw())) {
                    sql.append("and jb.YYSDBH in (select YYSDBH from pub_yysd_ssdr where ssdrssdw = '").append(queryVo.getDsrDw()).append("')");
                }


                sql.append("             ) a"+
                        "      ) tmp  " +
                        "  )tmpMain");
                System.out.println("收案------------------------");
                System.out.print(sql.toString());
                return sql.toString();
            }

        }
        public String lj_case(@Param("queryVo") ReportQueryVo queryVo){
            return loadLjCaseSql(queryVo,"ALL");
        }
        public String lj_end_case(@Param("queryVo") ReportQueryVo queryVo){
            return loadLjCaseSql(queryVo,"END");
        }
        public String lj_dsd_case(@Param("queryVo") ReportQueryVo queryVo){
            return loadLjCaseSql(queryVo,"DSD");
        }
        public String updateStatusByWayAndYysdbh(@Param("way") String way,@Param("yysdbh") Integer yysdbh){
            StringBuilder sql = new StringBuilder();
            sql.append("UPDATE PUB_YYSD_JB SET "+way+" ='ING' where YYSDBH="+yysdbh +" and "+way+" is null");
            return sql.toString();
        }
        public String report_repair(@Param("queryVo") ReportQueryVo queryVo){
            StringBuilder sql = new StringBuilder();
            sql.append("\n" +
                    "SELECT\n" +
                    "  FYBH fybh\n" +
                    "  ,sum(repairNum) \"repairNum\"\n" +
                    "  ,sum(repairSucNum) \"repairSucNum\"\n" +
                    "  ,sum(repairJtNum) \"repairJtNum\"\n" +
                    "  ,sum(repairBrNum) \"repairBrNum\"\n" +
                    "FROM (\n" +
                    "SELECT\n" +
                    "  FYBH\n" +
                    "  ,count(0) \"repairNum\"\n" +
                    "  ,count(CASE WHEN REPAIRSTATUS = 'RPBS003' THEN 1 END ) \"repairSucNum\"\n" +
                    "  ,0 \"repairJtNum\"\n" +
                    "  ,0 \"repairBrNum\"\n" +
                    "FROM (\n" +
                    "  SELECT\n" +
                    "    jb.FYBH,\n" +
                    "    repair.*\n" +
                    "  FROM PUB_REPAIR_INFO repair\n" +
                    "    LEFT JOIN PUB_YYSD_JB jb ON jb.YYSDBH = repair.YYSDBH\n" +
                    "\n" +
                    ") tmp\n" +
                    "GROUP BY FYBH\n" +
                    "UNION\n" +
                    "SELECT\n" +
                    "    FYBH\n" +
                    "    ,0 \"repairNum\"\n" +
                    "    ,0 \"repairSucNum\"\n" +
                    "    ,count(0) \"repairJtNum\"\n" +
                    "    ,count(CASE WHEN CALLSTATE = 1 THEN 1 END ) \"repairBrNum\"\n" +
                    "FROM PUB_WEB_CALL_INFO\n" +
                    "WHERE 1 = 1\n" +
                    "    AND OPERATORTYPE != 'ENTRY'\n" +
                    "    AND CALLDURATION > 0\n" +
                    "GROUP BY FYBH\n" +
                    "\n" +
                    ") tmpMain\n" +
                    "  WHERE FYBH is NOT NULL\n" +
                    "GROUP BY FYBH");
            return sql.toString();
        }
        public String report_lj(@Param("queryVo") ReportQueryVo queryVo){

            StringBuilder sql = new StringBuilder();
            String reportType = queryVo.getReportType();
            String groupCol;
            if(Objects.equals(reportType,"TS")){
                groupCol = " BMMC ";
            }else {
                groupCol = " YYRXM ";
            }
            sql.append("SELECT FYBH fybh,businessName")
                    .append(",sum(tmpMain.tsajNum) \"tsajNum\"") //累计推送案件
                    .append(",sum(tmpMain.chajNum) \"chajNum\"") //累计撤回案件
                    .append(",sum(tmpMain.drtsajNum) \"drtsajNum\"") //当日推送案件
                    .append(",sum(tmpMain.tssjrsNum) \"tssjrsNum\"") //累计推送涉及人数
                    .append(",sum(tmpMain.chsjrsNum) \"chsjrsNum\"") //累计撤回涉及人数
                    .append(",sum(tmpMain.drtssjrsNum) \"drtssjrsNum\"") //当日推送涉及人数
                    .append(",sum(tmpMain.fkcgNum) \"fkcgNum\"") //累计反馈送达成功的工单量
                    .append(",sum(tmpMain.fksbNum) \"fksbNum\"") //累计反馈送达失败的工单量
                    .append(" FROM ");
            sql.append(" ( ");
            //结果集1
            sql.append("SELECT FYBH, ").append(groupCol).append(" businessName")
                    .append(" ,count(0) \"tsajNum\"")
                    .append(" ,0 \"chajNum\"")
                    .append(" ,0 \"drtsajNum\"")
                    .append(" ,0 \"tssjrsNum\"")
                    .append(" ,0 \"chsjrsNum\"")
                    .append(" ,0 \"drtssjrsNum\"")
                    .append(" ,0 \"fkcgNum\"")
                    .append(" ,0 \"fksbNum\"")
                    .append("  FROM (" +
                            "      select FYBH,AJXH,BMMC,YYRXM FROM PUB_YYSD_JB jb" +
                            "      GROUP BY  jb.FYBH,jb.AJXH" +
                            "      ) tmp")
                    .append(" GROUP BY FYBH,").append(groupCol);

            sql.append(" UNION "); //连接

            //结果集2
            sql.append("SELECT FYBH, ").append(groupCol).append(" businessName")
                    .append(" ,0 \"tsajNum\"")
                    .append(" ,count(0) \"chajNum\"")
                    .append(" ,0 \"drtsajNum\"")
                    .append(" ,0 \"tssjrsNum\"")
                    .append(" ,0 \"chsjrsNum\"")
                    .append(" ,0 \"drtssjrsNum\"")
                    .append(" ,0 \"fkcgNum\"")
                    .append(" ,0 \"fksbNum\"")
                    .append("  FROM (" +
                            "       SELECT * FROM (select FYBH,AJXH,BMMC,YYRXM FROM PUB_YYSD_JB jb" +
                            "        WHERE jb.SDJG = 'X'" +
                            "        ) tmpA"+
                            "      GROUP BY  tmpA.FYBH,tmpA.AJXH" +
                            "      ) tmp")
                    .append(" GROUP BY FYBH,").append(groupCol);

            sql.append(" UNION "); //连接
            //结果集3
            sql.append("SELECT FYBH, ").append(groupCol).append(" businessName")
                    .append(" ,0 \"tsajNum\"")
                    .append(" ,0 \"chajNum\"")
                    .append(" ,count(0) \"drtsajNum\"")
                    .append(" ,0 \"tssjrsNum\"")
                    .append(" ,0 \"chsjrsNum\"")
                    .append(" ,0 \"drtssjrsNum\"")
                    .append(" ,0 \"fkcgNum\"")
                    .append(" ,0 \"fksbNum\"")
                    .append(" FROM (" +
                            "      SELECT * FROM (select FYBH,AJXH,BMMC,YYRXM FROM PUB_YYSD_JB jb" +
                            "        WHERE  to_char(now(),'yy.mm.dd') =  to_char(jb.YYSJ,'yy.mm.dd')" +
                            "        ) tmpA"+
                            "      GROUP BY  tmpA.FYBH,tmpA.AJXH" +
                            "      ) tmp")
                    .append(" GROUP BY FYBH,").append(groupCol);

            sql.append(" UNION "); //连接
            //结果集4
            sql.append("SELECT FYBH, ").append(groupCol).append(" businessName")
                    .append(" ,0 \"tsajNum\"")
                    .append(" ,0 \"chajNum\"")
                    .append(" ,0 \"drtsajNum\"")
                    .append(" ,count(0) \"tssjrsNum\"")
                    .append(" ,count(CASE WHEN jb.SDJG = 'X' THEN 1 END ) \"chsjrsNum\"")
                    .append(" ,count(case WHEN to_char(now(),'yy.mm.dd') =  to_char(jb.YYSJ,'yy.mm.dd') THEN 1 END ) \"drtssjrsNum\"")
                    .append(" ,0 \"fkcgNum\"")
                    .append(" ,0 \"fksbNum\"")
                    .append("   FROM PUB_YYSD_JB jb" +
                            "  LEFT JOIN PUB_YYSD_SSDR ssdr ON ssdr.YYSDBH = jb.YYSDBH")
                    .append(" GROUP BY FYBH,").append(groupCol);
            sql.append(" UNION "); //连接
            //结果集5
            sql.append("SELECT FYBH, ").append(groupCol).append(" businessName")
                    .append(" ,0 \"tsajNum\"")
                    .append(" ,0 \"chajNum\"")
                    .append(" ,0 \"drtsajNum\"")
                    .append(" ,0 \"tssjrsNum\"")
                    .append(" ,0 \"chsjrsNum\"")
                    .append(" ,0 \"drtssjrsNum\"")
                    .append(" ,count(CASE WHEN jb.SDJG = 'Y' THEN 1 END ) \"fkcgNum\"")
                    .append(" ,count(CASE WHEN jb.SDJG = 'N' THEN 1 END ) \"fksbNum\"")
                    .append("   FROM PUB_YYSD_JB jb ")
                    .append(" GROUP BY FYBH,").append(groupCol);

            sql.append(" ) tmpMain ")
                    .append("GROUP BY FYBH,tmpMain.businessName"); //聚合3个结果集


            return sql.toString();
        }
        public String getGdWclByGdryxm(@Param("gdryxm") String gdryxm,@Param("way") String way,@Param("emsyysdbh") Integer emsyysdbh) {
            StringBuilder sql = new StringBuilder();
            sql.append("select * from PUB_YYSD_JB where GDRYXM = '").append(gdryxm).append("' and SDJG is null and ")
                    .append(way).append(" not in ('Y','N')");
            if(null != emsyysdbh){
                sql.append(" and YYSDBH = "+emsyysdbh);
            }
            sql.append(" order by YYSDBH");
            return sql.toString();
        }
        public String updateSdcgByKey(@Param("yysdbh") Integer yysdbh, @Param("sdWay") String sdWay) {
            StringBuilder sql = new StringBuilder();
            sql.append("update PUB_YYSD_JB set ").append(sdWay).append(" ='Y'where YYSDBH =").append(yysdbh);
            return sql.toString();
        }
        public String updateYysdJbOfSdfk(@Param("jbEntity") PubYysdJbEntity jbEntity) {
            StringBuilder sql = new StringBuilder();
            sql.append("update PUB_YYSD_JB set ");
            Integer fkzt = jbEntity.getFkzt();
            sql.append(" FKZT = ").append(fkzt);
            if(Objects.equals(2,fkzt)){
                sql.append(",SDJG is NULL");
            }

            sql.append(" where YYSDBH = ").append(jbEntity.getYysdbh());
            return sql.toString();
        }
        public String updateSdsbByKey(@Param("yysdbh") Integer yysdbh, @Param("sdWay") String sdWay) {
            StringBuilder sql = new StringBuilder();
            sql.append("update PUB_YYSD_JB set ").append(sdWay).append(" ='N'where YYSDBH =").append(yysdbh);
            return sql.toString();
        }
        public String getGdYclByGdryxm(@Param("gdryxm") String gdryxm,@Param("way")String way,@Param("emsyysdbh")Integer emsyysdbh){
            StringBuilder sql = new StringBuilder();
            sql.append("select * from PUB_YYSD_JB where GDRYXM = '").append(gdryxm).append("' and (SDJG is not null or ")
                    .append(way).append(" in ('Y','N'))");
            if(null != emsyysdbh){
                sql.append(" and YYSDBH = "+emsyysdbh);
            }
            sql.append(" order by YYSDBH");
            return sql.toString();
        }
        public String getYysdListByGdryxm(@Param("gdryxm") String gdryxm){
            StringBuilder sql = new StringBuilder();
            sql.append("select * from PUB_YYSD_JB where SDJG is null and GDRYXM = '").append(gdryxm).append("'");
            sql.append(" order by YYSDBH");
            return sql.toString();
        }

        public String getYysdList(@Param("yysdbh") Integer yysdbh) {
            StringBuilder sql = new StringBuilder();
            sql.append("select * from PUB_YYSD_JB where YYSDBH = "+yysdbh);
            sql.append(" order by YYSDBH");
            return sql.toString();
        }


        public String findByCbrAndSdjg(@Param("yhmc") String yhmc, @Param("sdjg") Integer sdjg,@Param("fybh") String fybh){
            StringBuilder sql = new StringBuilder();sql.append("select * from PUB_YYSD_JB where (YYRXM = '"+yhmc+"' or CBR = '"+yhmc+"') and FYBH = '"+fybh+"' ");
            if(sdjg==2){
                sql.append(" and SDJG is NULL AND DHSD is NULL AND DZSD is NULL AND EMSSD is NULL AND GGSD is NULL AND ZJSD is NULL AND LYLQ is NULL AND WTSD is NULL AND ZHJSD is NULL AND DXSD is NULL");
            }
            if (sdjg==3){
                sql.append(" and SDJG is NULL and NOT ( DHSD is NULL AND DZSD is NULL AND EMSSD is NULL AND GGSD is NULL AND ZJSD is NULL AND LYLQ is NULL AND WTSD is NULL AND ZHJSD is NULL AND DXSD is NULL)");
            }
            if(sdjg==4){
                sql.append(" and SDJG in ('Y','N') and (FKZT != 1 or FKZT is NULL)");
            }
            if(sdjg==5){
                sql.append(" and SDJG in ('Y','N') and FKZT = 1");
            }
            if(sdjg==6){
                sql.append(" and SDJG = 'X'");
            }
            sql.append(" order by YYSDBH");
            return sql.toString();
        }
        public String getAssignedRecord(@Param("start") String start,  @Param("end") String end,@Param("fybh") String fybh){
            StringBuilder sql = new StringBuilder();
            sql.append("select * from PUB_YYSD_JB where GDRYXM is not null and YYSJ >= '"+start+"' and YYSJ <= '"+end+"'");
            if(!StringUtil.equals(fybh,"-1")){
                sql.append("and FYBH = '"+fybh+"'");
            }
            sql.append(" order by YYSDBH");
            return sql.toString();
        }
        public String getUndistributedRecord(@Param("start") String start,  @Param("end") String end,@Param("fybh") String fybh){
            StringBuilder sql = new StringBuilder();
            sql.append("select * from PUB_YYSD_JB where GDRYXM is  null and SDJG is null and YYSJ >= '"+start+"' and YYSJ <= '"+end+"'");
            if(!StringUtil.equals(fybh,"-1")){
                sql.append("and FYBH = '"+fybh+"'");
            }
            sql.append(" order by YYSDBH");
            return sql.toString();
        }
        public String  getGdcxResult(@Param("gdcxModel") GdcxModel gdcxModel){
            StringBuilder sql = new StringBuilder();
            sql.append("select JB.* from PUB_YYSD_JB as JB  where  ");
            sql.append("JB.YYSJ>= '").append(gdcxModel.getStartTime()).append("' ");
            sql.append(" and JB.YYSJ<= '").append(gdcxModel.getEndTime()).append("' ");
            if ((!StringUtil.equals(gdcxModel.getFybh(),"-1"))){
                sql.append(" and JB.FYBH = '").append(gdcxModel.getFybh()).append("' ");
            }
            if (gdcxModel.getYysdbh()!= null){
                sql.append(" and JB.YYSDBH = ").append(gdcxModel.getYysdbh());
            }
            if(!StringUtil.isBlank(gdcxModel.getAh())){
                sql.append(" and JB.AH like '%").append(gdcxModel.getAh()).append("%'");
            }
            if (!StringUtil.isBlank(gdcxModel.getAjmc())){
                sql.append(" and JB.AJMC like '%").append(gdcxModel.getAjmc()).append("%'");
            }
            if (!StringUtil.isBlank(gdcxModel.getYyr())){
                sql.append(" and JB.YYRXM like '%").append(gdcxModel.getYyr()).append("%'");
            }
            if (!StringUtil.isBlank(gdcxModel.getSsdr())){
                sql.append(" and JB.YYSDBH IN (SELECT YYSDBH FROM PUB_YYSD_SSDR WHERE PUB_YYSD_SSDR.SSDRMC like '%").append(gdcxModel.getSsdr()).append("%') ");
            }
            if(gdcxModel.getSdzt()!=null){
            if (gdcxModel.getSdzt()==0){
                sql.append(" and JB.SDJG is NULL AND JB.DHSD is NULL AND JB.DZSD is NULL AND JB.EMSSD is NULL AND JB.GGSD is NULL AND JB.ZJSD is NULL AND JB.LYLQ is NULL AND JB.WTSD is NULL AND JB.ZHJSD is NULL AND JB.DXSD is NULL");
            }
            if (gdcxModel.getSdzt()==1){
                sql.append(" and JB.SDJG is NULL and NOT ( JB.DHSD is NULL AND JB.DZSD is NULL AND JB.EMSSD is NULL AND JB.GGSD is NULL AND JB.ZJSD is NULL AND JB.LYLQ is NULL AND JB.WTSD is NULL AND JB.ZHJSD is NULL AND JB.DXSD is NULL)");
            }
            if (gdcxModel.getSdzt()==2){
                sql.append(" and JB.SDJG is not NULL");
            }
            }
            if(StringUtil.isNotBlank(gdcxModel.getSdr())){
                sql.append(" and JB.GDRYXM = '"+gdcxModel.getSdr()+"'");
            }

            sql.append(" order by JB.YYSDBH");
            return sql.toString();
        }

        public String  getTsyysdResult(@Param("gdcxModel") GdcxModel gdcxModel){
            StringBuilder sql = new StringBuilder();
            sql.append("select JB.* from PUB_YYSD_JB as JB  where JB.AJXH=-2 and ");
            sql.append("JB.YYSJ>= '").append(gdcxModel.getStartTime()).append("' ");
            sql.append(" and JB.YYSJ<= '").append(gdcxModel.getEndTime()).append("' ");
            if ((!StringUtil.equals(gdcxModel.getFybh(),"-1"))){
                sql.append(" and JB.FYBH = '").append(gdcxModel.getFybh()).append("' ");
            }
            if (gdcxModel.getYysdbh()!= null){
                sql.append(" and JB.YYSDBH = ").append(gdcxModel.getYysdbh());
            }
            if(!StringUtil.isBlank(gdcxModel.getAh())){
                sql.append(" and JB.AH like '%").append(gdcxModel.getAh()).append("%'");
            }
            if (!StringUtil.isBlank(gdcxModel.getAjmc())){
                sql.append(" and JB.AJMC like '%").append(gdcxModel.getAjmc()).append("%'");
            }
            if (!StringUtil.isBlank(gdcxModel.getYyr())){
                sql.append(" and JB.YYRXM like '%").append(gdcxModel.getYyr()).append("%'");
            }
            if (!StringUtil.isBlank(gdcxModel.getSsdr())){
                sql.append(" and JB.YYSDBH IN (SELECT YYSDBH FROM PUB_YYSD_SSDR WHERE PUB_YYSD_SSDR.SSDRMC like '%").append(gdcxModel.getSsdr()).append("%') ");
            }
            if(gdcxModel.getSdzt()!=null){
                if (gdcxModel.getSdzt()==0){
                    sql.append(" and JB.SDJG is NULL AND JB.DHSD is NULL AND JB.DZSD is NULL AND JB.EMSSD is NULL AND JB.GGSD is NULL AND JB.ZJSD is NULL AND JB.LYLQ is NULL AND JB.WTSD is NULL AND JB.ZHJSD is NULL AND JB.DXSD is NULL");
                }
                if (gdcxModel.getSdzt()==1){
                    sql.append(" and JB.SDJG is NULL and NOT ( JB.DHSD is NULL AND JB.DZSD is NULL AND JB.EMSSD is NULL AND JB.GGSD is NULL AND JB.ZJSD is NULL AND JB.LYLQ is NULL AND JB.WTSD is NULL AND JB.ZHJSD is NULL AND JB.DXSD is NULL)");
                }
                if (gdcxModel.getSdzt()==2){
                    sql.append(" and JB.SDJG is not NULL");
                }
            }
            if(StringUtil.isNotBlank(gdcxModel.getSdr())){
                sql.append(" and JB.GDRYXM = '"+gdcxModel.getSdr()+"'");
            }

            sql.append(" order by JB.YYSDBH");
            return sql.toString();
        }

        public String getFeedbackRecord(@Param("start") String start,  @Param("end") String end,@Param("fybh") String fybh){
            StringBuilder sql = new StringBuilder();
            sql.append("select jb.*,to_char(jb.YYSJ,'yy.mm.dd') as yysj,to_char(jb.sdsj,'yy.mm.dd') as sdsj, ry.yhmc as sdymc  , yyrxm as yyr from PUB_YYSD_JB jb left join PUB_YYSD_RYXX ry on jb.gdryxm = ry.yhdm where  SDJG in ('Y','N') and YYSJ >= '"+start+"' and YYSJ <= '"+end+"'");
            if(!StringUtil.equals(fybh,"-1")){
                sql.append("and jb.FYBH = '"+fybh+"'");
            }
            sql.append(" and yysj >= '"+start +"' and yysj <= '"+end+"' ");
            sql.append(" order by YYSDBH");
            return sql.toString();
        }

        public String getUnFeedbackRecord(@Param("start") String start,  @Param("end") String end,@Param("fybh") String fybh){
            StringBuilder sql = new StringBuilder();
            sql.append("select jb.*,to_char(jb.YYSJ,'yy.mm.dd') as yysj,to_char(jb.sdsj,'yy.mm.dd') as sdsj, ry.yhmc as sdymc , yyrxm as yyr from PUB_YYSD_JB jb left join PUB_YYSD_RYXX ry on jb.gdryxm = ry.yhdm where  SDJG in ('FY','FN') and YYSJ >= '"+start+"' and YYSJ <= '"+end+"'");
            if(!StringUtil.equals(fybh,"-1")){
                sql.append("and jb.FYBH = '"+fybh+"'");
            }
            sql.append(" and yysj >= '"+start +"' and yysj <= '"+end+"' ");
            sql.append(" order by YYSDBH");
            return sql.toString();
        }
    }


    //    SELECT jb.YYSDBH,ryxx.WWEMPID from PUB_YYSD_JB jb
    //    LEFT JOIN PUB_YYSD_RYXX ryxx ON jb.GDRYXM = ryxx.YHDM
    @Select(value = "SELECT jb.YYSDBH,ryxx.WWEMPID from PUB_YYSD_JB jb LEFT JOIN PUB_YYSD_RYXX ryxx ON jb.GDRYXM = ryxx.YHDM where jb.GDRYXM is not NULL order by jb.YYSDBH")
    List<YysdJbRyxxVO> getJbryxx();

    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE AJXH = #{ajxh} AND FYBH = #{fybh} AND ajxz = '调解'" )
    PubYysdJbEntity selectByAjxhAndFybh(Integer ajxh,String fybh);

    //本周新收案件
    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE GDRYXM = #{gdryxm} AND SDJG is null AND YYSJ >= (select CURRENT_DATE + cast(-1*(to_number(to_char(CURRENT_DATE,'D'),'99')-2)||'days' as interval)) order by YYSJ" )
    List<PubYysdJbEntity> selectNewAjThisWeek(String gdryxm);

    //催单案件
    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE GDRYXM = #{gdryxm} AND CDSJ notnull AND SDJG is null order by YYSJ" )
    List<PubYysdJbEntity> selectCdAjThisWeek(String gdryxm);

    //临期开庭
    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE GDRYXM = #{gdryxm}  AND SDJG is null AND KTSJ notnull and KTSJ !='空' and (to_date(KTSJ,'yyyy-mm-dd')) <= now() + interval '7 day' order by KTSJ" )
    List<PubYysdJbEntity> selectKtAjThisWeek(String gdryxm);

    //即将超审限
    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE GDRYXM = #{gdryxm}  AND SDJG is null AND YYSJ >= now() - interval '8 day' AND YYSJ <= now() - interval '6 day' order by YYSJ" )
    List<PubYysdJbEntity> selectJjCsxAjThisWeek(String gdryxm);

    //超审限
    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE GDRYXM = #{gdryxm}  AND SDJG is null AND YYSJ <= now() - interval '8 day' order by YYSJ" )
    List<PubYysdJbEntity> selectCsxAjThisWeek(String gdryxm);

    //邮寄物流异常
    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE GDRYXM = #{gdryxm}  AND SDJG is null AND (SELECT scrq FROM rpo_ems_info where rpo_ems_info.yysdbh = PUB_YYSD_JB.YYSDBH and rpo_ems_info.sdjg isnull order by rpo_ems_info.scrq limit 1) <= now() - interval '7 day' order by YYSJ" )
    List<PubYysdJbEntity> selectEMSYcAjThisWeek(String gdryxm);

    //文书缺失案件
    @Select(value = "SELECT * FROM PUB_YYSD_JB WHERE GDRYXM = #{gdryxm}  AND SDJG is null AND WSQS = 1 order by YYSJ" )
    List<PubYysdJbEntity> selectWsqsAjThisWeek(String gdryxm);


}