package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubYysdJbEntity;
import com.nju.sdpt.entity.PubZgysdLogEntity;
import com.nju.sdpt.entity.ZgysdLogEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.Date;

@Mapper
@Repository
public interface PubZgysdLogEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_LOG
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_LOG
     *
     * @mbggenerated
     */
    int insert(PubZgysdLogEntity record);

    void insertForFz(ZgysdLogEntity zgysdLogEntity);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_LOG
     *
     * @mbggenerated
     */
    int insertSelective(PubZgysdLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_LOG
     *
     * @mbggenerated
     */
    PubZgysdLogEntity selectByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubZgysdLogEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_LOG
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubZgysdLogEntity record);



    @Select("select B.* from PUB_ZGYSD_LOG A , PUB_YYSD_JB B where A.YYSDBH = B.YYSDBH and A.BH =#{logbh}")
    PubYysdJbEntity getYysdByAjid(@Param("logbh") Integer logbh);
}