package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubZgysdInfoEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface PubZgysdInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer zgysdbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_INFO
     *
     * @mbggenerated
     */
    int insert(PubZgysdInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PubZgysdInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_INFO
     *
     * @mbggenerated
     */
    PubZgysdInfoEntity selectByPrimaryKey(Integer zgysdbh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubZgysdInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZGYSD_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubZgysdInfoEntity record);

}