package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.PubZybInfoEntity;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface PubZybInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZYB_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer dxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZYB_INFO
     *
     * @mbggenerated
     */
    int insert(PubZybInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZYB_INFO
     *
     * @mbggenerated
     */
    int insertSelective(PubZybInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZYB_INFO
     *
     * @mbggenerated
     */
    PubZybInfoEntity selectByPrimaryKey(Integer dxid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZYB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PubZybInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUB_ZYB_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PubZybInfoEntity record);

    //查询图片集合
    @Select(value = "select * from PUB_ZYB_INFO where YWID =  #{ywid} and YWLX = 1")
    List<PubZybInfoEntity> selectZybList(@Param("ywid") String ywid);
    //回显图片
    @Select(value = "select * from PUB_ZYB_INFO where ID =  #{id}")
    PubZybInfoEntity selectZyb(@Param("id") Integer id);
}