package com.nju.sdpt.mapper;

import com.nju.sdpt.entity.RpoEmsInfoEntity;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface RpoEmsInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int insert(RpoEmsInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int insertSelective(RpoEmsInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    RpoEmsInfoEntity selectByPrimaryKey(Integer bh);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RpoEmsInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RPO_EMS_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RpoEmsInfoEntity record);

    @Select(value = "SELECT count(0) FROM RPO_EMS_INFO WHERE YYSDBH = ${yysdbh} AND KDID = ${kdid}")
    int selectCountByYYsdbhAndKdid(@Param("yysdbh") Integer yysdbh,@Param("kdid") Integer kdid);

    @Select(value = "SELECT bh FROM RPO_EMS_INFO WHERE YYSDBH = ${yysdbh} AND KDID = ${kdid} ")
    List<Integer> selectBh(@Param("yysdbh") Integer yysdbh, @Param("kdid") Integer kdid);

    @Delete(value = "DELETE FROM RPO_EMS_INFO WHERE YYSDBH = #{yysdbh} AND KDID = #{kdid}")
    boolean deleteRecordByYysdbhAndKdid(@Param("yysdbh")Integer yysdbh,@Param("kdid")Integer kdid);

    @Select(value = "SELECT * FROM RPO_EMS_INFO WHERE YYSDBH = ${yysdbh} AND KDID = ${kdid}")
    RpoEmsInfoEntity selectByKdidAndYysdbh(@Param("yysdbh")Integer yysdbh,@Param("kdid")Integer kdid);
}